package ru.it.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T15:41:37.569+06:00
 * Generated source version: 2.7.5
 *
 */
@WebService(targetNamespace = "http://it.ru/", name = "ItsWebServiceSoap")
@XmlSeeAlso({org.xmlsoap.schemas.soap.encoding.ObjectFactory.class, ru.it.abstracttypes.ObjectFactory.class, ObjectFactory.class})
public interface ItsWebServiceSoap {

    @WebResult(name = "LoadDocumentResult", targetNamespace = "http://it.ru/")
    @RequestWrapper(localName = "LoadDocument", targetNamespace = "http://it.ru/", className = "ru.it.LoadDocument")
    @WebMethod(operationName = "LoadDocument", action = "http://it.ru/LoadDocument")
    @ResponseWrapper(localName = "LoadDocumentResponse", targetNamespace = "http://it.ru/", className = "ru.it.LoadDocumentResponse")
    public boolean loadDocument(
        @WebParam(name = "authors", targetNamespace = "http://it.ru/")
        java.lang.String authors,
        @WebParam(name = "date", targetNamespace = "http://it.ru/")
        javax.xml.datatype.XMLGregorianCalendar date,
        @WebParam(name = "fileName", targetNamespace = "http://it.ru/")
        java.lang.String fileName,
        @WebParam(name = "content", targetNamespace = "http://it.ru/")
        byte[] content
    );

    @WebResult(name = "LoadPersonResult", targetNamespace = "http://it.ru/")
    @RequestWrapper(localName = "LoadPerson", targetNamespace = "http://it.ru/", className = "ru.it.LoadPerson")
    @WebMethod(operationName = "LoadPerson", action = "http://it.ru/LoadPerson")
    @ResponseWrapper(localName = "LoadPersonResponse", targetNamespace = "http://it.ru/", className = "ru.it.LoadPersonResponse")
    public int loadPerson(
        @WebParam(name = "person", targetNamespace = "http://it.ru/")
        ru.it.soap.PersonLoad person
    );

    @WebResult(name = "GetPersonsResult", targetNamespace = "http://it.ru/")
    @RequestWrapper(localName = "GetPersons", targetNamespace = "http://it.ru/", className = "ru.it.GetPersons")
    @WebMethod(operationName = "GetPersons", action = "http://it.ru/GetPersons")
    @ResponseWrapper(localName = "GetPersonsResponse", targetNamespace = "http://it.ru/", className = "ru.it.GetPersonsResponse")
    public ru.it.soap.ArrayOfPerson getPersons();

    @RequestWrapper(localName = "LoadFile", targetNamespace = "http://it.ru/", className = "ru.it.LoadFile")
    @WebMethod(operationName = "LoadFile", action = "http://it.ru/LoadFile")
    @ResponseWrapper(localName = "LoadFileResponse", targetNamespace = "http://it.ru/", className = "ru.it.LoadFileResponse")
    public void loadFile(
        @WebParam(name = "fileName", targetNamespace = "http://it.ru/")
        java.lang.String fileName,
        @WebParam(name = "content", targetNamespace = "http://it.ru/")
        byte[] content
    );

    @WebResult(name = "GetDepartmentsResult", targetNamespace = "http://it.ru/")
    @RequestWrapper(localName = "GetDepartments", targetNamespace = "http://it.ru/", className = "ru.it.GetDepartments")
    @WebMethod(operationName = "GetDepartments", action = "http://it.ru/GetDepartments")
    @ResponseWrapper(localName = "GetDepartmentsResponse", targetNamespace = "http://it.ru/", className = "ru.it.GetDepartmentsResponse")
    public ru.it.soap.ArrayOfDepartment getDepartments();

    @WebResult(name = "LoadDepartmentResult", targetNamespace = "http://it.ru/")
    @RequestWrapper(localName = "LoadDepartment", targetNamespace = "http://it.ru/", className = "ru.it.LoadDepartment")
    @WebMethod(operationName = "LoadDepartment", action = "http://it.ru/LoadDepartment")
    @ResponseWrapper(localName = "LoadDepartmentResponse", targetNamespace = "http://it.ru/", className = "ru.it.LoadDepartmentResponse")
    public int loadDepartment(
        @WebParam(name = "dep", targetNamespace = "http://it.ru/")
        ru.it.soap.DepartmentLoad dep
    );

    @WebResult(name = "GetVersionResult", targetNamespace = "http://it.ru/")
    @RequestWrapper(localName = "GetVersion", targetNamespace = "http://it.ru/", className = "ru.it.GetVersion")
    @WebMethod(operationName = "GetVersion", action = "http://it.ru/GetVersion")
    @ResponseWrapper(localName = "GetVersionResponse", targetNamespace = "http://it.ru/", className = "ru.it.GetVersionResponse")
    public java.lang.String getVersion();

    @WebResult(name = "LoadMailResult", targetNamespace = "http://it.ru/")
    @RequestWrapper(localName = "LoadMail", targetNamespace = "http://it.ru/", className = "ru.it.LoadMail")
    @WebMethod(operationName = "LoadMail", action = "http://it.ru/LoadMail")
    @ResponseWrapper(localName = "LoadMailResponse", targetNamespace = "http://it.ru/", className = "ru.it.LoadMailResponse")
    public boolean loadMail(
        @WebParam(name = "from", targetNamespace = "http://it.ru/")
        java.lang.String from,
        @WebParam(name = "to", targetNamespace = "http://it.ru/")
        java.lang.String to,
        @WebParam(name = "date", targetNamespace = "http://it.ru/")
        javax.xml.datatype.XMLGregorianCalendar date,
        @WebParam(name = "mailText", targetNamespace = "http://it.ru/")
        java.lang.String mailText,
        @WebParam(name = "attachFileName", targetNamespace = "http://it.ru/")
        ru.it.soap.ArrayOfString attachFileName,
        @WebParam(name = "attachContent", targetNamespace = "http://it.ru/")
        ru.it.soap.ArrayOfBase64Binary attachContent
    );

    @WebResult(name = "GetInfoResult", targetNamespace = "http://it.ru/")
    @RequestWrapper(localName = "GetInfo", targetNamespace = "http://it.ru/", className = "ru.it.GetInfo")
    @WebMethod(operationName = "GetInfo", action = "http://it.ru/GetInfo")
    @ResponseWrapper(localName = "GetInfoResponse", targetNamespace = "http://it.ru/", className = "ru.it.GetInfoResponse")
    public ru.it.soap.Info getInfo();

    @WebResult(name = "LoadCallResult", targetNamespace = "http://it.ru/")
    @RequestWrapper(localName = "LoadCall", targetNamespace = "http://it.ru/", className = "ru.it.LoadCall")
    @WebMethod(operationName = "LoadCall", action = "http://it.ru/LoadCall")
    @ResponseWrapper(localName = "LoadCallResponse", targetNamespace = "http://it.ru/", className = "ru.it.LoadCallResponse")
    public boolean loadCall(
        @WebParam(name = "phoneFrom", targetNamespace = "http://it.ru/")
        java.lang.String phoneFrom,
        @WebParam(name = "phoneTo", targetNamespace = "http://it.ru/")
        java.lang.String phoneTo,
        @WebParam(name = "date", targetNamespace = "http://it.ru/")
        javax.xml.datatype.XMLGregorianCalendar date,
        @WebParam(name = "dur", targetNamespace = "http://it.ru/")
        int dur
    );

    @RequestWrapper(localName = "LoadPersonPhoto", targetNamespace = "http://it.ru/", className = "ru.it.LoadPersonPhoto")
    @WebMethod(operationName = "LoadPersonPhoto", action = "http://it.ru/LoadPersonPhoto")
    @ResponseWrapper(localName = "LoadPersonPhotoResponse", targetNamespace = "http://it.ru/", className = "ru.it.LoadPersonPhotoResponse")
    public void loadPersonPhoto(
        @WebParam(name = "personId", targetNamespace = "http://it.ru/")
        int personId,
        @WebParam(name = "photo", targetNamespace = "http://it.ru/")
        byte[] photo
    );

    @WebResult(name = "GetPersonPhotoResult", targetNamespace = "http://it.ru/")
    @RequestWrapper(localName = "GetPersonPhoto", targetNamespace = "http://it.ru/", className = "ru.it.GetPersonPhoto")
    @WebMethod(operationName = "GetPersonPhoto", action = "http://it.ru/GetPersonPhoto")
    @ResponseWrapper(localName = "GetPersonPhotoResponse", targetNamespace = "http://it.ru/", className = "ru.it.GetPersonPhotoResponse")
    public byte[] getPersonPhoto(
        @WebParam(name = "personId", targetNamespace = "http://it.ru/")
        int personId,
        @WebParam(name = "thumbnail", targetNamespace = "http://it.ru/")
        boolean thumbnail
    );

    @WebResult(name = "LoadPersonsFromActiveDirectoryResult", targetNamespace = "http://it.ru/")
    @RequestWrapper(localName = "LoadPersonsFromActiveDirectory", targetNamespace = "http://it.ru/", className = "ru.it.LoadPersonsFromActiveDirectory")
    @WebMethod(operationName = "LoadPersonsFromActiveDirectory", action = "http://it.ru/LoadPersonsFromActiveDirectory")
    @ResponseWrapper(localName = "LoadPersonsFromActiveDirectoryResponse", targetNamespace = "http://it.ru/", className = "ru.it.LoadPersonsFromActiveDirectoryResponse")
    public boolean loadPersonsFromActiveDirectory();

    @WebResult(name = "GetPersonSignificItemsResult", targetNamespace = "http://it.ru/")
    @RequestWrapper(localName = "GetPersonSignificItems", targetNamespace = "http://it.ru/", className = "ru.it.GetPersonSignificItems")
    @WebMethod(operationName = "GetPersonSignificItems", action = "http://it.ru/GetPersonSignificItems")
    @ResponseWrapper(localName = "GetPersonSignificItemsResponse", targetNamespace = "http://it.ru/", className = "ru.it.GetPersonSignificItemsResponse")
    public ru.it.soap.ArrayOfDataItem getPersonSignificItems(
        @WebParam(name = "personId", targetNamespace = "http://it.ru/")
        int personId
    );

    @WebResult(name = "GetPersonLinksResult", targetNamespace = "http://it.ru/")
    @RequestWrapper(localName = "GetPersonLinks", targetNamespace = "http://it.ru/", className = "ru.it.GetPersonLinks")
    @WebMethod(operationName = "GetPersonLinks", action = "http://it.ru/GetPersonLinks")
    @ResponseWrapper(localName = "GetPersonLinksResponse", targetNamespace = "http://it.ru/", className = "ru.it.GetPersonLinksResponse")
    public ru.it.soap.ArrayOfPersonsLink getPersonLinks(
        @WebParam(name = "personId", targetNamespace = "http://it.ru/")
        int personId
    );

    @RequestWrapper(localName = "UploadIndex", targetNamespace = "http://it.ru/", className = "ru.it.UploadIndex")
    @WebMethod(operationName = "UploadIndex", action = "http://it.ru/UploadIndex")
    @ResponseWrapper(localName = "UploadIndexResponse", targetNamespace = "http://it.ru/", className = "ru.it.UploadIndexResponse")
    public void uploadIndex();

    @WebResult(name = "FindPersonResult", targetNamespace = "http://it.ru/")
    @RequestWrapper(localName = "FindPerson", targetNamespace = "http://it.ru/", className = "ru.it.FindPerson")
    @WebMethod(operationName = "FindPerson", action = "http://it.ru/FindPerson")
    @ResponseWrapper(localName = "FindPersonResponse", targetNamespace = "http://it.ru/", className = "ru.it.FindPersonResponse")
    public ru.it.soap.Person findPerson(
        @WebParam(name = "value", targetNamespace = "http://it.ru/")
        java.lang.String value,
        @WebParam(name = "innerId", targetNamespace = "http://it.ru/")
        int innerId
    );

    @WebResult(name = "SearchExpertsResult", targetNamespace = "http://it.ru/")
    @RequestWrapper(localName = "SearchExperts", targetNamespace = "http://it.ru/", className = "ru.it.SearchExperts")
    @WebMethod(operationName = "SearchExperts", action = "http://it.ru/SearchExperts")
    @ResponseWrapper(localName = "SearchExpertsResponse", targetNamespace = "http://it.ru/", className = "ru.it.SearchExpertsResponse")
    public ru.it.soap.ArrayOfPerson searchExperts(
        @WebParam(name = "text", targetNamespace = "http://it.ru/")
        java.lang.String text
    );

    @WebResult(name = "SearchFileExpertsResult", targetNamespace = "http://it.ru/")
    @RequestWrapper(localName = "SearchFileExperts", targetNamespace = "http://it.ru/", className = "ru.it.SearchFileExperts")
    @WebMethod(operationName = "SearchFileExperts", action = "http://it.ru/SearchFileExperts")
    @ResponseWrapper(localName = "SearchFileExpertsResponse", targetNamespace = "http://it.ru/", className = "ru.it.SearchFileExpertsResponse")
    public ru.it.soap.ArrayOfPerson searchFileExperts(
        @WebParam(name = "fileName", targetNamespace = "http://it.ru/")
        java.lang.String fileName,
        @WebParam(name = "content", targetNamespace = "http://it.ru/")
        byte[] content
    );

    @RequestWrapper(localName = "LoadPost", targetNamespace = "http://it.ru/", className = "ru.it.LoadPost")
    @WebMethod(operationName = "LoadPost", action = "http://it.ru/LoadPost")
    @ResponseWrapper(localName = "LoadPostResponse", targetNamespace = "http://it.ru/", className = "ru.it.LoadPostResponse")
    public void loadPost(
        @WebParam(name = "post", targetNamespace = "http://it.ru/")
        ru.it.soap.PersonPostLoad post
    );

    @WebResult(name = "LoadCommunicationResult", targetNamespace = "http://it.ru/")
    @RequestWrapper(localName = "LoadCommunication", targetNamespace = "http://it.ru/", className = "ru.it.LoadCommunication")
    @WebMethod(operationName = "LoadCommunication", action = "http://it.ru/LoadCommunication")
    @ResponseWrapper(localName = "LoadCommunicationResponse", targetNamespace = "http://it.ru/", className = "ru.it.LoadCommunicationResponse")
    public boolean loadCommunication(
        @WebParam(name = "com", targetNamespace = "http://it.ru/")
        ru.it.soap.CommunicationLoad com
    );
}
