package ru.it.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T15:41:37.621+06:00
 * Generated source version: 2.7.5
 *
 */
@WebService(targetNamespace = "http://it.ru/", name = "ItsWebServiceHttpGet")
@XmlSeeAlso({org.xmlsoap.schemas.soap.encoding.ObjectFactory.class, ru.it.abstracttypes.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ItsWebServiceHttpGet {

    @WebResult(name = "ArrayOfPerson", targetNamespace = "http://it.ru/", partName = "Body")
    @WebMethod(operationName = "GetPersons")
    public ArrayOfPerson getPersons();

    @WebMethod(operationName = "LoadFile")
    public void loadFile(
        @WebParam(partName = "fileName", name = "fileName", targetNamespace = "http://it.ru/")
        java.lang.String fileName,
        @WebParam(partName = "content", name = "content", targetNamespace = "http://it.ru/")
        ru.it.abstracttypes.StringArray content
    );

    @WebResult(name = "ArrayOfDepartment", targetNamespace = "http://it.ru/", partName = "Body")
    @WebMethod(operationName = "GetDepartments")
    public ArrayOfDepartment getDepartments();

    @WebResult(name = "string", targetNamespace = "http://it.ru/", partName = "Body")
    @WebMethod(operationName = "GetVersion")
    public java.lang.String getVersion();

    @WebResult(name = "Info", targetNamespace = "http://it.ru/", partName = "Body")
    @WebMethod(operationName = "GetInfo")
    public Info getInfo();

    @WebResult(name = "boolean", targetNamespace = "http://it.ru/", partName = "Body")
    @WebMethod(operationName = "LoadCall")
    public boolean loadCall(
        @WebParam(partName = "phoneFrom", name = "phoneFrom", targetNamespace = "http://it.ru/")
        java.lang.String phoneFrom,
        @WebParam(partName = "phoneTo", name = "phoneTo", targetNamespace = "http://it.ru/")
        java.lang.String phoneTo,
        @WebParam(partName = "date", name = "date", targetNamespace = "http://it.ru/")
        java.lang.String date,
        @WebParam(partName = "dur", name = "dur", targetNamespace = "http://it.ru/")
        java.lang.String dur
    );

    @WebMethod(operationName = "LoadPersonPhoto")
    public void loadPersonPhoto(
        @WebParam(partName = "personId", name = "personId", targetNamespace = "http://it.ru/")
        java.lang.String personId,
        @WebParam(partName = "photo", name = "photo", targetNamespace = "http://it.ru/")
        ru.it.abstracttypes.StringArray photo
    );

    @WebResult(name = "base64Binary", targetNamespace = "http://it.ru/", partName = "Body")
    @WebMethod(operationName = "GetPersonPhoto")
    public byte[] getPersonPhoto(
        @WebParam(partName = "personId", name = "personId", targetNamespace = "http://it.ru/")
        java.lang.String personId,
        @WebParam(partName = "thumbnail", name = "thumbnail", targetNamespace = "http://it.ru/")
        java.lang.String thumbnail
    );

    @WebResult(name = "boolean", targetNamespace = "http://it.ru/", partName = "Body")
    @WebMethod(operationName = "LoadPersonsFromActiveDirectory")
    public boolean loadPersonsFromActiveDirectory();

    @WebResult(name = "ArrayOfPerson", targetNamespace = "http://it.ru/", partName = "Body")
    @WebMethod(operationName = "SearchExperts")
    public ArrayOfPerson searchExperts(
        @WebParam(partName = "text", name = "text", targetNamespace = "http://it.ru/")
        java.lang.String text
    );

    @WebResult(name = "ArrayOfDataItem", targetNamespace = "http://it.ru/", partName = "Body")
    @WebMethod(operationName = "GetPersonSignificItems")
    public ArrayOfDataItem getPersonSignificItems(
        @WebParam(partName = "personId", name = "personId", targetNamespace = "http://it.ru/")
        java.lang.String personId
    );

    @WebResult(name = "ArrayOfPersonsLink", targetNamespace = "http://it.ru/", partName = "Body")
    @WebMethod(operationName = "GetPersonLinks")
    public ArrayOfPersonsLink getPersonLinks(
        @WebParam(partName = "personId", name = "personId", targetNamespace = "http://it.ru/")
        java.lang.String personId
    );

    @WebResult(name = "ArrayOfPerson", targetNamespace = "http://it.ru/", partName = "Body")
    @WebMethod(operationName = "SearchFileExperts")
    public ArrayOfPerson searchFileExperts(
        @WebParam(partName = "fileName", name = "fileName", targetNamespace = "http://it.ru/")
        java.lang.String fileName,
        @WebParam(partName = "content", name = "content", targetNamespace = "http://it.ru/")
        ru.it.abstracttypes.StringArray content
    );

    @WebMethod(operationName = "UploadIndex")
    public void uploadIndex();

    @WebResult(name = "Person", targetNamespace = "http://it.ru/", partName = "Body")
    @WebMethod(operationName = "FindPerson")
    public Person findPerson(
        @WebParam(partName = "value", name = "value", targetNamespace = "http://it.ru/")
        java.lang.String value,
        @WebParam(partName = "innerId", name = "innerId", targetNamespace = "http://it.ru/")
        java.lang.String innerId
    );
}
