
package ru.it.lecm.experts.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SearchExpertsServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SearchExpertsServiceSoap {


    /**
     * 
     * @param id
     * @return
     *     returns ru.it.lecm.experts.cl.RequestExpertResponse.RequestExpertResult
     */
    @WebMethod(action = "http://tempuri.org/requestExpert")
    @WebResult(name = "requestExpertResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "requestExpert", targetNamespace = "http://tempuri.org/", className = "ru.it.lecm.experts.cl.RequestExpert")
    @ResponseWrapper(localName = "requestExpertResponse", targetNamespace = "http://tempuri.org/", className = "ru.it.lecm.experts.cl.RequestExpertResponse")
    public RequestExpertResponse.RequestExpertResult requestExpert(
		    @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
		    int id);

    /**
     * 
     * @param query
     * @return
     *     returns ru.it.lecm.experts.cl.RequestExpertsResponse.RequestExpertsResult
     */
    @WebMethod(action = "http://tempuri.org/requestExperts")
    @WebResult(name = "requestExpertsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "requestExperts", targetNamespace = "http://tempuri.org/", className = "ru.it.lecm.experts.cl.RequestExperts")
    @ResponseWrapper(localName = "requestExpertsResponse", targetNamespace = "http://tempuri.org/", className = "ru.it.lecm.experts.cl.RequestExpertsResponse")
    public RequestExpertsResponse.RequestExpertsResult requestExperts(
		    @WebParam(name = "query", targetNamespace = "http://tempuri.org/")
		    String query);

    /**
     * 
     * @param min
     * @param fileName
     * @param binData
     * @return
     *     returns ru.it.lecm.experts.cl.RequestExpertsExResponse.RequestExpertsExResult
     */
    @WebMethod(action = "http://tempuri.org/requestExpertsEx")
    @WebResult(name = "requestExpertsExResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "requestExpertsEx", targetNamespace = "http://tempuri.org/", className = "ru.it.lecm.experts.cl.RequestExpertsEx")
    @ResponseWrapper(localName = "requestExpertsExResponse", targetNamespace = "http://tempuri.org/", className = "ru.it.lecm.experts.cl.RequestExpertsExResponse")
    public RequestExpertsExResponse.RequestExpertsExResult requestExpertsEx(
		    @WebParam(name = "binData", targetNamespace = "http://tempuri.org/")
		    byte[] binData,
		    @WebParam(name = "fileName", targetNamespace = "http://tempuri.org/")
		    String fileName,
		    @WebParam(name = "min", targetNamespace = "http://tempuri.org/")
		    boolean min);

    /**
     * 
     * @param min
     * @param uri
     * @return
     *     returns ru.it.lecm.experts.cl.RequestExpertsByURIResponse.RequestExpertsByURIResult
     */
    @WebMethod(action = "http://tempuri.org/requestExpertsByURI")
    @WebResult(name = "requestExpertsByURIResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "requestExpertsByURI", targetNamespace = "http://tempuri.org/", className = "ru.it.lecm.experts.cl.RequestExpertsByURI")
    @ResponseWrapper(localName = "requestExpertsByURIResponse", targetNamespace = "http://tempuri.org/", className = "ru.it.lecm.experts.cl.RequestExpertsByURIResponse")
    public RequestExpertsByURIResponse.RequestExpertsByURIResult requestExpertsByURI(
		    @WebParam(name = "uri", targetNamespace = "http://tempuri.org/")
		    String uri,
		    @WebParam(name = "min", targetNamespace = "http://tempuri.org/")
		    boolean min);

    /**
     * 
     * @param coef
     * @param term
     * @param query
     * @return
     *     returns ru.it.lecm.experts.cl.RequestExpertsCoefTermResponse.RequestExpertsCoefTermResult
     */
    @WebMethod(action = "http://tempuri.org/requestExpertsCoefTerm")
    @WebResult(name = "requestExpertsCoefTermResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "requestExpertsCoefTerm", targetNamespace = "http://tempuri.org/", className = "ru.it.lecm.experts.cl.RequestExpertsCoefTerm")
    @ResponseWrapper(localName = "requestExpertsCoefTermResponse", targetNamespace = "http://tempuri.org/", className = "ru.it.lecm.experts.cl.RequestExpertsCoefTermResponse")
    public RequestExpertsCoefTermResponse.RequestExpertsCoefTermResult requestExpertsCoefTerm(
		    @WebParam(name = "query", targetNamespace = "http://tempuri.org/")
		    String query,
		    @WebParam(name = "term", targetNamespace = "http://tempuri.org/")
		    String term,
		    @WebParam(name = "coef", targetNamespace = "http://tempuri.org/")
		    float coef);

}
