
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "GateWcfServiceHttps", targetNamespace = "http://tempuri.org/", wsdlLocation = "file:/D:/work/laboratory/GateFlat/GateFlat.svc")
public class GateWcfServiceHttps
    extends Service
{

    private final static URL GATEWCFSERVICEHTTPS_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.tempuri.GateWcfServiceHttps.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.tempuri.GateWcfServiceHttps.class.getResource(".");
            url = new URL(baseUrl, "file:/D:/work/laboratory/GateFlat/GateFlat.svc");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/D:/work/laboratory/GateFlat/GateFlat.svc', retrying as a local file");
            logger.warning(e.getMessage());
        }
        GATEWCFSERVICEHTTPS_WSDL_LOCATION = url;
    }

    public GateWcfServiceHttps(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GateWcfServiceHttps() {
        super(GATEWCFSERVICEHTTPS_WSDL_LOCATION, new QName("http://tempuri.org/", "GateWcfServiceHttps"));
    }

    /**
     * 
     * @return
     *     returns IGateWcfService
     */
    @WebEndpoint(name = "WSHttpBinding_IGateWcfService")
    public IGateWcfService getWSHttpBindingIGateWcfService() {
        return super.getPort(new QName("http://tempuri.org/", "WSHttpBinding_IGateWcfService"), IGateWcfService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGateWcfService
     */
    @WebEndpoint(name = "WSHttpBinding_IGateWcfService")
    public IGateWcfService getWSHttpBindingIGateWcfService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "WSHttpBinding_IGateWcfService"), IGateWcfService.class, features);
    }

}
