
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.microsoft.schemas.serialization.arrays.ArrayOfguid;
import com.microsoft.schemas.serialization.arrays.ArrayOfstring;
import ucloud.gate.proxy.ArrayOfDocflowInfoBase;
import ucloud.gate.proxy.ArrayOfDocumentInfo;
import ucloud.gate.proxy.ArrayOfOperatorInfo;
import ucloud.gate.proxy.ArrayOfRegistrationInfo;
import ucloud.gate.proxy.CompanyInfo;
import ucloud.gate.proxy.DocumentContent;
import ucloud.gate.proxy.DocumentToSend;
import ucloud.gate.proxy.DocumentTransportData;
import ucloud.gate.proxy.OperatorInfo;
import ucloud.gate.proxy.WorkspaceFilter;
import ucloud.gate.proxy.docflow.ReceivedDocumentInfo;
import ucloud.gate.proxy.exceptions.GateResponse;
import ucloud.gate.proxy.generating.documents.GeneratedDocument;
import ucloud.gate.proxy.generating.documents.Signer;
import ucloud.gate.proxy.generating.documents.common.ParticipantBase;
import ucloud.gate.proxy.generating.documents.invoice.CorrectionRequest;
import ucloud.gate.proxy.generating.documents.invoice.InvoiceGen;
import ucloud.gate.proxy.invoice.classes.Torg12BuyerTitleInfo;
import ucloud.gate.proxy.invoice.classes.Torg12SellerTitleInfo;
import ucloud.gate.proxy.registration.RegisterRequestForeignCert;
import ucloud.gate.proxy.registration.RegisterResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IGateWcfService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ucloud.gate.proxy.common.ObjectFactory.class,
    ucloud.gate.proxy.generating.documents.ObjectFactory.class,
    ucloud.gate.proxy.ObjectFactory.class,
    ucloud.gate.proxy.exceptions.ObjectFactory.class,
    ucloud.gate.proxy.registration.ObjectFactory.class,
    ucloud.gate.proxy.invoice.ObjectFactory.class,
    com.microsoft.schemas.serialization.ObjectFactory.class,
    com.microsoft.schemas.serialization.arrays.ObjectFactory.class,
    ucloud.gate.proxy.docflow.ObjectFactory.class,
    org.tempuri.ObjectFactory.class,
    ucloud.gate.proxy.generating.documents.invoice.ObjectFactory.class,
    ucloud.gate.proxy.invoice.classes.ObjectFactory.class,
    ucloud.gate.proxy.generating.documents.common.ObjectFactory.class
})
public interface IGateWcfService {


    /**
     * 
     * @param getServiceVersionResult
     * @param version
     */
    @WebMethod(operationName = "GetServiceVersion", action = "http://tempuri.org/IGateWcfService/GetServiceVersion")
    @RequestWrapper(localName = "GetServiceVersion", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetServiceVersion")
    @ResponseWrapper(localName = "GetServiceVersionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetServiceVersionResponse")
    public void getServiceVersion(
        @WebParam(name = "GetServiceVersionResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<GateResponse> getServiceVersionResult,
        @WebParam(name = "version", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> version);

    /**
     * 
     * @return
     *     returns ucloud.gate.proxy.exceptions.GateResponse
     */
    @WebMethod(operationName = "ClearMailBox", action = "http://tempuri.org/IGateWcfService/ClearMailBox")
    @WebResult(name = "ClearMailBoxResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ClearMailBox", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ClearMailBox")
    @ResponseWrapper(localName = "ClearMailBoxResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ClearMailBoxResponse")
    public GateResponse clearMailBox();

    /**
     * 
     * @param token
     * @param operatorCode
     * @param authenticateByCertificateResult
     * @param signedData
     * @param signature
     */
    @WebMethod(operationName = "AuthenticateByCertificate", action = "http://tempuri.org/IGateWcfService/AuthenticateByCertificate")
    @RequestWrapper(localName = "AuthenticateByCertificate", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AuthenticateByCertificate")
    @ResponseWrapper(localName = "AuthenticateByCertificateResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AuthenticateByCertificateResponse")
    public void authenticateByCertificate(
        @WebParam(name = "operatorCode", targetNamespace = "http://tempuri.org/")
        String operatorCode,
        @WebParam(name = "signature", targetNamespace = "http://tempuri.org/")
        byte[] signature,
        @WebParam(name = "signedData", targetNamespace = "http://tempuri.org/")
        String signedData,
        @WebParam(name = "AuthenticateByCertificateResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<GateResponse> authenticateByCertificateResult,
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> token);

    /**
     * 
     * @param sign
     * @param organizationEdoId
     * @param operatorCode
     * @param userId
     * @param organizationId
     * @param registerUserByCertificateResult
     * @param organizationKpp
     * @param organizationInn
     * @param partnerKey
     */
    @WebMethod(operationName = "RegisterUserByCertificate", action = "http://tempuri.org/IGateWcfService/RegisterUserByCertificate")
    @RequestWrapper(localName = "RegisterUserByCertificate", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RegisterUserByCertificate")
    @ResponseWrapper(localName = "RegisterUserByCertificateResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RegisterUserByCertificateResponse")
    public void registerUserByCertificate(
        @WebParam(name = "operatorCode", targetNamespace = "http://tempuri.org/")
        String operatorCode,
        @WebParam(name = "partnerKey", targetNamespace = "http://tempuri.org/")
        String partnerKey,
        @WebParam(name = "organizationInn", targetNamespace = "http://tempuri.org/")
        String organizationInn,
        @WebParam(name = "organizationKpp", targetNamespace = "http://tempuri.org/")
        String organizationKpp,
        @WebParam(name = "sign", targetNamespace = "http://tempuri.org/")
        byte[] sign,
        @WebParam(name = "userId", targetNamespace = "http://tempuri.org/")
        String userId,
        @WebParam(name = "RegisterUserByCertificateResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<GateResponse> registerUserByCertificateResult,
        @WebParam(name = "organizationId", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> organizationId,
        @WebParam(name = "organizationEdoId", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> organizationEdoId);

    /**
     * 
     * @param inn
     * @param operatorCode
     * @param kpp
     * @param mobileNumber
     * @return
     *     returns ucloud.gate.proxy.exceptions.GateResponse
     */
    @WebMethod(operationName = "StartRegisterUserBySms", action = "http://tempuri.org/IGateWcfService/StartRegisterUserBySms")
    @WebResult(name = "StartRegisterUserBySmsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "StartRegisterUserBySms", targetNamespace = "http://tempuri.org/", className = "org.tempuri.StartRegisterUserBySms")
    @ResponseWrapper(localName = "StartRegisterUserBySmsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.StartRegisterUserBySmsResponse")
    public GateResponse startRegisterUserBySms(
        @WebParam(name = "operatorCode", targetNamespace = "http://tempuri.org/")
        String operatorCode,
        @WebParam(name = "mobileNumber", targetNamespace = "http://tempuri.org/")
        String mobileNumber,
        @WebParam(name = "inn", targetNamespace = "http://tempuri.org/")
        String inn,
        @WebParam(name = "kpp", targetNamespace = "http://tempuri.org/")
        String kpp);

    /**
     * 
     * @param inn
     * @param organizationEdoId
     * @param operatorCode
     * @param kpp
     * @param userIdByPartnerSystem
     * @param organizationId
     * @param mobileNumber
     * @param password
     * @param finishRegisterUserBySmsResult
     * @param partnerKey
     */
    @WebMethod(operationName = "FinishRegisterUserBySms", action = "http://tempuri.org/IGateWcfService/FinishRegisterUserBySms")
    @RequestWrapper(localName = "FinishRegisterUserBySms", targetNamespace = "http://tempuri.org/", className = "org.tempuri.FinishRegisterUserBySms")
    @ResponseWrapper(localName = "FinishRegisterUserBySmsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.FinishRegisterUserBySmsResponse")
    public void finishRegisterUserBySms(
        @WebParam(name = "operatorCode", targetNamespace = "http://tempuri.org/")
        String operatorCode,
        @WebParam(name = "mobileNumber", targetNamespace = "http://tempuri.org/")
        String mobileNumber,
        @WebParam(name = "partnerKey", targetNamespace = "http://tempuri.org/")
        String partnerKey,
        @WebParam(name = "inn", targetNamespace = "http://tempuri.org/")
        String inn,
        @WebParam(name = "kpp", targetNamespace = "http://tempuri.org/")
        String kpp,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "userIdByPartnerSystem", targetNamespace = "http://tempuri.org/")
        String userIdByPartnerSystem,
        @WebParam(name = "FinishRegisterUserBySmsResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<GateResponse> finishRegisterUserBySmsResult,
        @WebParam(name = "organizationId", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> organizationId,
        @WebParam(name = "organizationEdoId", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> organizationEdoId);

    /**
     * 
     * @param sendRegisterRequestResult
     * @param requestId
     * @param operatorCode
     * @param signature
     * @param requestBinary
     */
    @WebMethod(operationName = "SendRegisterRequest", action = "http://tempuri.org/IGateWcfService/SendRegisterRequest")
    @RequestWrapper(localName = "SendRegisterRequest", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendRegisterRequest")
    @ResponseWrapper(localName = "SendRegisterRequestResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendRegisterRequestResponse")
    public void sendRegisterRequest(
        @WebParam(name = "requestBinary", targetNamespace = "http://tempuri.org/")
        byte[] requestBinary,
        @WebParam(name = "signature", targetNamespace = "http://tempuri.org/")
        byte[] signature,
        @WebParam(name = "operatorCode", targetNamespace = "http://tempuri.org/")
        String operatorCode,
        @WebParam(name = "SendRegisterRequestResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<GateResponse> sendRegisterRequestResult,
        @WebParam(name = "requestId", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> requestId);

    /**
     * 
     * @param getRegisterResponseResult
     * @param packetId
     * @param operatorCode
     * @param operatorResponse
     */
    @WebMethod(operationName = "GetRegisterResponse", action = "http://tempuri.org/IGateWcfService/GetRegisterResponse")
    @RequestWrapper(localName = "GetRegisterResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRegisterResponse")
    @ResponseWrapper(localName = "GetRegisterResponseResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRegisterResponseResponse")
    public void getRegisterResponse(
        @WebParam(name = "packetId", targetNamespace = "http://tempuri.org/")
        String packetId,
        @WebParam(name = "operatorCode", targetNamespace = "http://tempuri.org/")
        String operatorCode,
        @WebParam(name = "GetRegisterResponseResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<GateResponse> getRegisterResponseResult,
        @WebParam(name = "operatorResponse", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<RegisterResponse> operatorResponse);

    /**
     * 
     * @param content
     * @param generateRegisterRequestResult
     * @param operatorCode
     * @param request
     */
    @WebMethod(operationName = "GenerateRegisterRequest", action = "http://tempuri.org/IGateWcfService/GenerateRegisterRequest")
    @RequestWrapper(localName = "GenerateRegisterRequest", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GenerateRegisterRequest")
    @ResponseWrapper(localName = "GenerateRegisterRequestResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GenerateRegisterRequestResponse")
    public void generateRegisterRequest(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        RegisterRequestForeignCert request,
        @WebParam(name = "operatorCode", targetNamespace = "http://tempuri.org/")
        String operatorCode,
        @WebParam(name = "GenerateRegisterRequestResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<GateResponse> generateRegisterRequestResult,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<byte[]> content);

    /**
     * 
     * @param operatorCode
     * @param sendDocumentResult
     * @param doc
     * @param billingTicket
     * @param documentId
     */
    @WebMethod(operationName = "SendDocument", action = "http://tempuri.org/IGateWcfService/SendDocument")
    @RequestWrapper(localName = "SendDocument", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendDocument")
    @ResponseWrapper(localName = "SendDocumentResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendDocumentResponse")
    public void sendDocument(
        @WebParam(name = "doc", targetNamespace = "http://tempuri.org/")
        DocumentToSend doc,
        @WebParam(name = "operatorCode", targetNamespace = "http://tempuri.org/")
        String operatorCode,
        @WebParam(name = "billingTicket", targetNamespace = "http://tempuri.org/")
        String billingTicket,
        @WebParam(name = "SendDocumentResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<GateResponse> sendDocumentResult,
        @WebParam(name = "documentId", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> documentId);

    /**
     * 
     * @param sender
     * @param getDocumentTransportDataResult
     * @param receiver
     * @param prefferableOperatorCode
     * @param transportData
     */
    @WebMethod(operationName = "GetDocumentTransportData", action = "http://tempuri.org/IGateWcfService/GetDocumentTransportData")
    @RequestWrapper(localName = "GetDocumentTransportData", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDocumentTransportData")
    @ResponseWrapper(localName = "GetDocumentTransportDataResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDocumentTransportDataResponse")
    public void getDocumentTransportData(
        @WebParam(name = "sender", targetNamespace = "http://tempuri.org/")
        CompanyInfo sender,
        @WebParam(name = "receiver", targetNamespace = "http://tempuri.org/")
        CompanyInfo receiver,
        @WebParam(name = "prefferableOperatorCode", targetNamespace = "http://tempuri.org/")
        String prefferableOperatorCode,
        @WebParam(name = "GetDocumentTransportDataResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<GateResponse> getDocumentTransportDataResult,
        @WebParam(name = "transportData", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<DocumentTransportData> transportData);

    /**
     * 
     * @param sender
     * @param operatorCodes
     * @param receiver
     * @param getMutualOperatorsResult
     */
    @WebMethod(operationName = "GetMutualOperators", action = "http://tempuri.org/IGateWcfService/GetMutualOperators")
    @RequestWrapper(localName = "GetMutualOperators", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetMutualOperators")
    @ResponseWrapper(localName = "GetMutualOperatorsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetMutualOperatorsResponse")
    public void getMutualOperators(
        @WebParam(name = "sender", targetNamespace = "http://tempuri.org/")
        CompanyInfo sender,
        @WebParam(name = "receiver", targetNamespace = "http://tempuri.org/")
        CompanyInfo receiver,
        @WebParam(name = "GetMutualOperatorsResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<GateResponse> getMutualOperatorsResult,
        @WebParam(name = "operatorCodes", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<ArrayOfstring> operatorCodes);

    /**
     * 
     * @param docflows
     * @param getDocflowListResult
     * @param filter
     */
    @WebMethod(operationName = "GetDocflowList", action = "http://tempuri.org/IGateWcfService/GetDocflowList")
    @RequestWrapper(localName = "GetDocflowList", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDocflowList")
    @ResponseWrapper(localName = "GetDocflowListResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDocflowListResponse")
    public void getDocflowList(
        @WebParam(name = "filter", targetNamespace = "http://tempuri.org/")
        WorkspaceFilter filter,
        @WebParam(name = "GetDocflowListResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<GateResponse> getDocflowListResult,
        @WebParam(name = "docflows", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<ArrayOfDocflowInfoBase> docflows);

    /**
     * 
     * @param docflowIdArray
     * @return
     *     returns ucloud.gate.proxy.exceptions.GateResponse
     */
    @WebMethod(operationName = "MarkDocflowsAsRead", action = "http://tempuri.org/IGateWcfService/MarkDocflowsAsRead")
    @WebResult(name = "MarkDocflowsAsReadResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "MarkDocflowsAsRead", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MarkDocflowsAsRead")
    @ResponseWrapper(localName = "MarkDocflowsAsReadResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MarkDocflowsAsReadResponse")
    public GateResponse markDocflowsAsRead(
        @WebParam(name = "docflowIdArray", targetNamespace = "http://tempuri.org/")
        ArrayOfguid docflowIdArray);

    /**
     * 
     * @param getDocumentListResult
     * @param documentInfos
     * @param docflowId
     */
    @WebMethod(operationName = "GetDocumentList", action = "http://tempuri.org/IGateWcfService/GetDocumentList")
    @RequestWrapper(localName = "GetDocumentList", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDocumentList")
    @ResponseWrapper(localName = "GetDocumentListResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDocumentListResponse")
    public void getDocumentList(
        @WebParam(name = "docflowId", targetNamespace = "http://tempuri.org/")
        String docflowId,
        @WebParam(name = "GetDocumentListResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<GateResponse> getDocumentListResult,
        @WebParam(name = "documentInfos", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<ArrayOfDocumentInfo> documentInfos);

    /**
     * 
     * @param getSignaturesOnly
     * @param getDocumentContentResult
     * @param documentId
     * @param docContent
     */
    @WebMethod(operationName = "GetDocumentContent", action = "http://tempuri.org/IGateWcfService/GetDocumentContent")
    @RequestWrapper(localName = "GetDocumentContent", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDocumentContent")
    @ResponseWrapper(localName = "GetDocumentContentResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDocumentContentResponse")
    public void getDocumentContent(
        @WebParam(name = "documentId", targetNamespace = "http://tempuri.org/")
        String documentId,
        @WebParam(name = "getSignaturesOnly", targetNamespace = "http://tempuri.org/")
        Boolean getSignaturesOnly,
        @WebParam(name = "GetDocumentContentResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<GateResponse> getDocumentContentResult,
        @WebParam(name = "docContent", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<DocumentContent> docContent);

    /**
     * 
     * @param getOperatorsResult
     * @param operatorInfos
     */
    @WebMethod(operationName = "GetOperators", action = "http://tempuri.org/IGateWcfService/GetOperators")
    @RequestWrapper(localName = "GetOperators", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOperators")
    @ResponseWrapper(localName = "GetOperatorsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOperatorsResponse")
    public void getOperators(
        @WebParam(name = "GetOperatorsResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<GateResponse> getOperatorsResult,
        @WebParam(name = "operatorInfos", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<ArrayOfOperatorInfo> operatorInfos);

    /**
     * 
     * @param registrationInfos
     * @param getRegistrationInfoResult
     */
    @WebMethod(operationName = "GetRegistrationInfo", action = "http://tempuri.org/IGateWcfService/GetRegistrationInfo")
    @RequestWrapper(localName = "GetRegistrationInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRegistrationInfo")
    @ResponseWrapper(localName = "GetRegistrationInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRegistrationInfoResponse")
    public void getRegistrationInfo(
        @WebParam(name = "GetRegistrationInfoResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<GateResponse> getRegistrationInfoResult,
        @WebParam(name = "registrationInfos", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<ArrayOfRegistrationInfo> registrationInfos);

    /**
     * 
     * @param operatorCode
     * @param invoice
     * @param generatedDoc
     * @param generateInvoiceXmlResult
     */
    @WebMethod(operationName = "GenerateInvoiceXml", action = "http://tempuri.org/IGateWcfService/GenerateInvoiceXml")
    @RequestWrapper(localName = "GenerateInvoiceXml", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GenerateInvoiceXml")
    @ResponseWrapper(localName = "GenerateInvoiceXmlResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GenerateInvoiceXmlResponse")
    public void generateInvoiceXml(
        @WebParam(name = "invoice", targetNamespace = "http://tempuri.org/")
        InvoiceGen invoice,
        @WebParam(name = "operatorCode", targetNamespace = "http://tempuri.org/")
        String operatorCode,
        @WebParam(name = "GenerateInvoiceXmlResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<GateResponse> generateInvoiceXmlResult,
        @WebParam(name = "generatedDoc", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<DocumentToSend> generatedDoc);

    /**
     * 
     * @param generatedDocDate
     * @param parentDocument
     * @param signer
     * @param senderCompany
     * @param generateNotificationXmlResult
     * @param operatorCode
     * @param generatedDoc
     */
    @WebMethod(operationName = "GenerateNotificationXml", action = "http://tempuri.org/IGateWcfService/GenerateNotificationXml")
    @RequestWrapper(localName = "GenerateNotificationXml", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GenerateNotificationXml")
    @ResponseWrapper(localName = "GenerateNotificationXmlResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GenerateNotificationXmlResponse")
    public void generateNotificationXml(
        @WebParam(name = "signer", targetNamespace = "http://tempuri.org/")
        Signer signer,
        @WebParam(name = "senderCompany", targetNamespace = "http://tempuri.org/")
        ParticipantBase senderCompany,
        @WebParam(name = "parentDocument", targetNamespace = "http://tempuri.org/")
        ReceivedDocumentInfo parentDocument,
        @WebParam(name = "generatedDocDate", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar generatedDocDate,
        @WebParam(name = "operatorCode", targetNamespace = "http://tempuri.org/")
        String operatorCode,
        @WebParam(name = "GenerateNotificationXmlResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<GateResponse> generateNotificationXmlResult,
        @WebParam(name = "generatedDoc", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<GeneratedDocument> generatedDoc);

    /**
     * 
     * @param parseInvoiceCorrectionRequestXmlResult
     * @param requestText
     * @param xml
     */
    @WebMethod(operationName = "ParseInvoiceCorrectionRequestXml", action = "http://tempuri.org/IGateWcfService/ParseInvoiceCorrectionRequestXml")
    @RequestWrapper(localName = "ParseInvoiceCorrectionRequestXml", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ParseInvoiceCorrectionRequestXml")
    @ResponseWrapper(localName = "ParseInvoiceCorrectionRequestXmlResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ParseInvoiceCorrectionRequestXmlResponse")
    public void parseInvoiceCorrectionRequestXml(
        @WebParam(name = "xml", targetNamespace = "http://tempuri.org/")
        byte[] xml,
        @WebParam(name = "ParseInvoiceCorrectionRequestXmlResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<GateResponse> parseInvoiceCorrectionRequestXmlResult,
        @WebParam(name = "requestText", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> requestText);

    /**
     * 
     * @param generateInvoiceCorrectionRequestXmlResult
     * @param generatedDocument
     * @param correctionRequest
     */
    @WebMethod(operationName = "GenerateInvoiceCorrectionRequestXml", action = "http://tempuri.org/IGateWcfService/GenerateInvoiceCorrectionRequestXml")
    @RequestWrapper(localName = "GenerateInvoiceCorrectionRequestXml", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GenerateInvoiceCorrectionRequestXml")
    @ResponseWrapper(localName = "GenerateInvoiceCorrectionRequestXmlResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GenerateInvoiceCorrectionRequestXmlResponse")
    public void generateInvoiceCorrectionRequestXml(
        @WebParam(name = "correctionRequest", targetNamespace = "http://tempuri.org/")
        CorrectionRequest correctionRequest,
        @WebParam(name = "GenerateInvoiceCorrectionRequestXmlResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<GateResponse> generateInvoiceCorrectionRequestXmlResult,
        @WebParam(name = "generatedDocument", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<GeneratedDocument> generatedDocument);

    /**
     * 
     * @param signerInfo
     * @param content
     * @param verifySignatureResult
     * @param operatorCode
     * @param isSignatureValid
     * @param signature
     */
    @WebMethod(operationName = "VerifySignature", action = "http://tempuri.org/IGateWcfService/VerifySignature")
    @RequestWrapper(localName = "VerifySignature", targetNamespace = "http://tempuri.org/", className = "org.tempuri.VerifySignature")
    @ResponseWrapper(localName = "VerifySignatureResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.VerifySignatureResponse")
    public void verifySignature(
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        byte[] content,
        @WebParam(name = "signature", targetNamespace = "http://tempuri.org/")
        byte[] signature,
        @WebParam(name = "operatorCode", targetNamespace = "http://tempuri.org/")
        String operatorCode,
        @WebParam(name = "VerifySignatureResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<GateResponse> verifySignatureResult,
        @WebParam(name = "signerInfo", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> signerInfo,
        @WebParam(name = "isSignatureValid", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<Boolean> isSignatureValid);

    /**
     * 
     * @param operatorCode
     * @return
     *     returns ucloud.gate.proxy.exceptions.GateResponse
     */
    @WebMethod(operationName = "StartSmsAuthentication", action = "http://tempuri.org/IGateWcfService/StartSmsAuthentication")
    @WebResult(name = "StartSmsAuthenticationResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "StartSmsAuthentication", targetNamespace = "http://tempuri.org/", className = "org.tempuri.StartSmsAuthentication")
    @ResponseWrapper(localName = "StartSmsAuthenticationResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.StartSmsAuthenticationResponse")
    public GateResponse startSmsAuthentication(
        @WebParam(name = "operatorCode", targetNamespace = "http://tempuri.org/")
        String operatorCode);

    /**
     * 
     * @param token
     * @param operatorCode
     * @param finishSmsAuthenticationResult
     * @param password
     */
    @WebMethod(operationName = "FinishSmsAuthentication", action = "http://tempuri.org/IGateWcfService/FinishSmsAuthentication")
    @RequestWrapper(localName = "FinishSmsAuthentication", targetNamespace = "http://tempuri.org/", className = "org.tempuri.FinishSmsAuthentication")
    @ResponseWrapper(localName = "FinishSmsAuthenticationResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.FinishSmsAuthenticationResponse")
    public void finishSmsAuthentication(
        @WebParam(name = "operatorCode", targetNamespace = "http://tempuri.org/")
        String operatorCode,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "FinishSmsAuthenticationResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<GateResponse> finishSmsAuthenticationResult,
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> token);

    /**
     * 
     * @param opInfo
     * @param generateTorg12XmlForSellerResult
     * @param generatedDoc
     * @param date
     * @param vendorId
     * @param buyerId
     * @param info
     */
    @WebMethod(operationName = "GenerateTorg12XmlForSeller", action = "http://tempuri.org/IGateWcfService/GenerateTorg12XmlForSeller")
    @RequestWrapper(localName = "GenerateTorg12XmlForSeller", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GenerateTorg12XmlForSeller")
    @ResponseWrapper(localName = "GenerateTorg12XmlForSellerResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GenerateTorg12XmlForSellerResponse")
    public void generateTorg12XmlForSeller(
        @WebParam(name = "vendorId", targetNamespace = "http://tempuri.org/")
        String vendorId,
        @WebParam(name = "buyerId", targetNamespace = "http://tempuri.org/")
        String buyerId,
        @WebParam(name = "opInfo", targetNamespace = "http://tempuri.org/")
        OperatorInfo opInfo,
        @WebParam(name = "date", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar date,
        @WebParam(name = "info", targetNamespace = "http://tempuri.org/")
        Torg12SellerTitleInfo info,
        @WebParam(name = "GenerateTorg12XmlForSellerResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<GateResponse> generateTorg12XmlForSellerResult,
        @WebParam(name = "generatedDoc", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<GeneratedDocument> generatedDoc);

    /**
     * 
     * @param opInfo
     * @param generateTorg12XmlForBuyerResult
     * @param generatedDocument
     * @param date
     * @param vendorId
     * @param buyerId
     * @param info
     */
    @WebMethod(operationName = "GenerateTorg12XmlForBuyer", action = "http://tempuri.org/IGateWcfService/GenerateTorg12XmlForBuyer")
    @RequestWrapper(localName = "GenerateTorg12XmlForBuyer", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GenerateTorg12XmlForBuyer")
    @ResponseWrapper(localName = "GenerateTorg12XmlForBuyerResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GenerateTorg12XmlForBuyerResponse")
    public void generateTorg12XmlForBuyer(
        @WebParam(name = "vendorId", targetNamespace = "http://tempuri.org/")
        String vendorId,
        @WebParam(name = "buyerId", targetNamespace = "http://tempuri.org/")
        String buyerId,
        @WebParam(name = "opInfo", targetNamespace = "http://tempuri.org/")
        OperatorInfo opInfo,
        @WebParam(name = "date", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar date,
        @WebParam(name = "info", targetNamespace = "http://tempuri.org/")
        Torg12BuyerTitleInfo info,
        @WebParam(name = "GenerateTorg12XmlForBuyerResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<GateResponse> generateTorg12XmlForBuyerResult,
        @WebParam(name = "generatedDocument", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<GeneratedDocument> generatedDocument);

    /**
     * 
     * @param content
     * @param signDocumentResult
     * @param operatorCode
     * @param signature
     */
    @WebMethod(operationName = "SignDocument", action = "http://tempuri.org/IGateWcfService/SignDocument")
    @RequestWrapper(localName = "SignDocument", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SignDocument")
    @ResponseWrapper(localName = "SignDocumentResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SignDocumentResponse")
    public void signDocument(
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        byte[] content,
        @WebParam(name = "operatorCode", targetNamespace = "http://tempuri.org/")
        String operatorCode,
        @WebParam(name = "SignDocumentResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<GateResponse> signDocumentResult,
        @WebParam(name = "signature", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<byte[]> signature);

    /**
     * 
     * @param billingLogin
     * @param operatorCode
     * @param billingPassword
     * @param signature
     * @param existedAccount
     * @return
     *     returns ucloud.gate.proxy.exceptions.GateResponse
     */
    @WebMethod(operationName = "SetBillingAccountToOrganization", action = "http://tempuri.org/IGateWcfService/SetBillingAccountToOrganization")
    @WebResult(name = "SetBillingAccountToOrganizationResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SetBillingAccountToOrganization", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SetBillingAccountToOrganization")
    @ResponseWrapper(localName = "SetBillingAccountToOrganizationResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SetBillingAccountToOrganizationResponse")
    public GateResponse setBillingAccountToOrganization(
        @WebParam(name = "operatorCode", targetNamespace = "http://tempuri.org/")
        String operatorCode,
        @WebParam(name = "signature", targetNamespace = "http://tempuri.org/")
        byte[] signature,
        @WebParam(name = "billingLogin", targetNamespace = "http://tempuri.org/")
        String billingLogin,
        @WebParam(name = "billingPassword", targetNamespace = "http://tempuri.org/")
        String billingPassword,
        @WebParam(name = "existedAccount", targetNamespace = "http://tempuri.org/")
        Boolean existedAccount);

    /**
     * 
     * @param certificate
     * @param operatorCode
     * @param checkIfPersonIsEmployeeByCertificateResult
     * @param organizationKpp
     * @param isEmployee
     * @param organizationInn
     */
    @WebMethod(operationName = "CheckIfPersonIsEmployeeByCertificate", action = "http://tempuri.org/IGateWcfService/CheckIfPersonIsEmployeeByCertificate")
    @RequestWrapper(localName = "CheckIfPersonIsEmployeeByCertificate", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CheckIfPersonIsEmployeeByCertificate")
    @ResponseWrapper(localName = "CheckIfPersonIsEmployeeByCertificateResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CheckIfPersonIsEmployeeByCertificateResponse")
    public void checkIfPersonIsEmployeeByCertificate(
        @WebParam(name = "certificate", targetNamespace = "http://tempuri.org/")
        byte[] certificate,
        @WebParam(name = "operatorCode", targetNamespace = "http://tempuri.org/")
        String operatorCode,
        @WebParam(name = "organizationInn", targetNamespace = "http://tempuri.org/")
        String organizationInn,
        @WebParam(name = "organizationKpp", targetNamespace = "http://tempuri.org/")
        String organizationKpp,
        @WebParam(name = "CheckIfPersonIsEmployeeByCertificateResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<GateResponse> checkIfPersonIsEmployeeByCertificateResult,
        @WebParam(name = "isEmployee", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<Boolean> isEmployee);

}
