
package ru.it.lecm.mobile.services.documentManager;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WS_DocumentManagerService",
        targetNamespace = "urn:DefaultNamespace",
        wsdlLocation = "file:WSBR_DocumentManager.wsdl")
public class WSDocumentManagerService
    extends Service
{

    private final static URL WSDOCUMENTMANAGERSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSDOCUMENTMANAGERSERVICE_EXCEPTION;
    private final static QName WSDOCUMENTMANAGERSERVICE_QNAME = new QName("urn:DefaultNamespace", "WS_DocumentManagerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:WSBR_DocumentManager.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSDOCUMENTMANAGERSERVICE_WSDL_LOCATION = url;
        WSDOCUMENTMANAGERSERVICE_EXCEPTION = e;
    }

    public WSDocumentManagerService() {
        super(__getWsdlLocation(), WSDOCUMENTMANAGERSERVICE_QNAME);
    }

    public WSDocumentManagerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSDOCUMENTMANAGERSERVICE_QNAME, features);
    }

    public WSDocumentManagerService(URL wsdlLocation) {
        super(wsdlLocation, WSDOCUMENTMANAGERSERVICE_QNAME);
    }

    public WSDocumentManagerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSDOCUMENTMANAGERSERVICE_QNAME, features);
    }

    public WSDocumentManagerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSDocumentManagerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSDocumentManager
     */
    @WebEndpoint(name = "Domino")
    public WSDocumentManager getDomino() {
        return super.getPort(new QName("urn:DefaultNamespace", "Domino"), WSDocumentManager.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSDocumentManager
     */
    @WebEndpoint(name = "Domino")
    public WSDocumentManager getDomino(WebServiceFeature... features) {
        return super.getPort(new QName("urn:DefaultNamespace", "Domino"), WSDocumentManager.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSDOCUMENTMANAGERSERVICE_EXCEPTION!= null) {
            throw WSDOCUMENTMANAGERSERVICE_EXCEPTION;
        }
        return WSDOCUMENTMANAGERSERVICE_WSDL_LOCATION;
    }

}
