
package ru.it.lecm.mobile.services.formExecutor;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WS_ActionExecutorService",
        targetNamespace = "urn:DefaultNamespace",
        wsdlLocation = "file:WSBR_FormActionExecutor.wsdl")
public class WSActionExecutorService
    extends Service
{

    private final static URL WSACTIONEXECUTORSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSACTIONEXECUTORSERVICE_EXCEPTION;
    private final static QName WSACTIONEXECUTORSERVICE_QNAME = new QName("urn:DefaultNamespace", "WS_ActionExecutorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:WSBR_FormActionExecutor.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSACTIONEXECUTORSERVICE_WSDL_LOCATION = url;
        WSACTIONEXECUTORSERVICE_EXCEPTION = e;
    }

    public WSActionExecutorService() {
        super(__getWsdlLocation(), WSACTIONEXECUTORSERVICE_QNAME);
    }

    public WSActionExecutorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSACTIONEXECUTORSERVICE_QNAME, features);
    }

    public WSActionExecutorService(URL wsdlLocation) {
        super(wsdlLocation, WSACTIONEXECUTORSERVICE_QNAME);
    }

    public WSActionExecutorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSACTIONEXECUTORSERVICE_QNAME, features);
    }

    public WSActionExecutorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSActionExecutorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSActionExecutor
     */
    @WebEndpoint(name = "Domino")
    public WSActionExecutor getDomino() {
        return super.getPort(new QName("urn:DefaultNamespace", "Domino"), WSActionExecutor.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSActionExecutor
     */
    @WebEndpoint(name = "Domino")
    public WSActionExecutor getDomino(WebServiceFeature... features) {
        return super.getPort(new QName("urn:DefaultNamespace", "Domino"), WSActionExecutor.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSACTIONEXECUTORSERVICE_EXCEPTION!= null) {
            throw WSACTIONEXECUTORSERVICE_EXCEPTION;
        }
        return WSACTIONEXECUTORSERVICE_WSDL_LOCATION;
    }

}
