
package ru.it.lecm.mobile.services.formExecutor;

import ru.it.lecm.mobile.objects.*;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WS_ActionExecutor", targetNamespace = "urn:DefaultNamespace")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSActionExecutor {


    /**
     * 
     * @return
     *     returns ru.it.lecm.mobile.services.formExecutor.WSOEDS
     */
    @WebMethod(operationName = "GETFAKESIGN")
    @WebResult(name = "GETFAKESIGNReturn", partName = "GETFAKESIGNReturn")
    public WSOEDS getfakesign();

    /**
     * 
     * @param context
     * @param action
     * @param object
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "EXECUTE_")
    @WebResult(name = "EXECUTE_Return", partName = "EXECUTE_Return")
    public boolean execute(
        @WebParam(name = "OBJECT", partName = "OBJECT")
        WSOBJECT object,
        @WebParam(name = "ACTION", partName = "ACTION")
        WSOFORMACTION action,
        @WebParam(name = "CONTEXT", partName = "CONTEXT")
        WSOCONTEXT context);

    /**
     * 
     * @return
     *     returns ru.it.lecm.mobile.services.formExecutor.WSOITEM
     */
    @WebMethod(operationName = "GETITEM")
    @WebResult(name = "GETITEMReturn", partName = "GETITEMReturn")
    public WSOITEM getitem();

}
