
package ru.it.lecm.mobile.services.taskManager;

import ru.it.lecm.mobile.objects.*;

import java.math.BigInteger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WS_TaskManager", targetNamespace = "urn:DefaultNamespace")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSTaskManager {


    /**
     * 
     * @return
     *     returns ru.it.lecm.mobile.services.taskManager.WSOEDS
     */
    @WebMethod(operationName = "GETFAKESIGN", action = "GETFAKESIGN")
    @WebResult(name = "GETFAKESIGNReturn", partName = "GETFAKESIGNReturn")
    public WSOEDS getfakesign();

    /**
     * 
     * @param includeattachments
     * @param idtask
     * @param context
     * @return
     *     returns ru.it.lecm.mobile.services.taskManager.WSOTASK
     */
    @WebMethod(operationName = "GETTASK", action = "GETTASK")
    @WebResult(name = "GETTASKReturn", partName = "GETTASKReturn")
    public WSOTASK gettask(
        @WebParam(name = "IDTASK", partName = "IDTASK")
        String idtask,
        @WebParam(name = "INCLUDEATTACHMENTS", partName = "INCLUDEATTACHMENTS")
        boolean includeattachments,
        @WebParam(name = "CONTEXT", partName = "CONTEXT")
        WSOCONTEXT context);

    /**
     * 
     * @param docid
     * @param context
     * @param ismobject
     * @return
     *     returns ru.it.lecm.mobile.services.taskManager.WSOCOLLECTION
     */
    @WebMethod(operationName = "GETTASKSBYDOC", action = "GETTASKSBYDOC")
    @WebResult(name = "GETTASKSBYDOCReturn", partName = "GETTASKSBYDOCReturn")
    public WSOCOLLECTION gettasksbydoc(
        @WebParam(name = "DOCID", partName = "DOCID")
        String docid,
        @WebParam(name = "ISMOBJECT", partName = "ISMOBJECT")
        boolean ismobject,
        @WebParam(name = "CONTEXT", partName = "CONTEXT")
        WSOCONTEXT context);

    /**
     * 
     * @param includeattachments
     * @param roottaskid
     * @param context
     * @param childslevel
     * @param ismobject
     * @return
     *     returns ru.it.lecm.mobile.services.taskManager.WSOTASK
     */
    @WebMethod(operationName = "GETSTRUCTURE", action = "GETSTRUCTURE")
    @WebResult(name = "GETSTRUCTUREReturn", partName = "GETSTRUCTUREReturn")
    public WSOTASK getstructure(
        @WebParam(name = "ROOTTASKID", partName = "ROOTTASKID")
        String roottaskid,
        @WebParam(name = "CHILDSLEVEL", partName = "CHILDSLEVEL")
        BigInteger childslevel,
        @WebParam(name = "ISMOBJECT", partName = "ISMOBJECT")
        boolean ismobject,
        @WebParam(name = "INCLUDEATTACHMENTS", partName = "INCLUDEATTACHMENTS")
        boolean includeattachments,
        @WebParam(name = "CONTEXT", partName = "CONTEXT")
        WSOCONTEXT context);

    /**
     * 
     * @param newtask
     * @param docid
     * @param context
     * @param parenttaskid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CREATERESOLUTION", action = "CREATERESOLUTION")
    @WebResult(name = "CREATERESOLUTIONReturn", partName = "CREATERESOLUTIONReturn")
    public String createresolution(
        @WebParam(name = "DOCID", partName = "DOCID")
        String docid,
        @WebParam(name = "NEWTASK", partName = "NEWTASK")
        WSOTASK newtask,
        @WebParam(name = "PARENTTASKID", partName = "PARENTTASKID")
        String parenttaskid,
        @WebParam(name = "CONTEXT", partName = "CONTEXT")
        WSOCONTEXT context);

    /**
     * 
     * @param newtask
     * @param missionlabelid
     * @param context
     * @return
     *     returns ru.it.lecm.mobile.services.taskManager.WSOMTASK
     */
    @WebMethod(operationName = "UPDATERESOLUTION", action = "UPDATERESOLUTION")
    @WebResult(name = "UPDATERESOLUTIONReturn", partName = "UPDATERESOLUTIONReturn")
    public WSOMTASK updateresolution(
        @WebParam(name = "MISSIONLABELID", partName = "MISSIONLABELID")
        String missionlabelid,
        @WebParam(name = "NEWTASK", partName = "NEWTASK")
        WSOTASK newtask,
        @WebParam(name = "CONTEXT", partName = "CONTEXT")
        WSOCONTEXT context);

    /**
     * 
     * @param missionlabelid
     * @param context
     * @return
     *     returns ru.it.lecm.mobile.services.taskManager.WSOMTASK
     */
    @WebMethod(operationName = "DELETERESOLUTION", action = "DELETERESOLUTION")
    @WebResult(name = "DELETERESOLUTIONReturn", partName = "DELETERESOLUTIONReturn")
    public WSOMTASK deleteresolution(
        @WebParam(name = "MISSIONLABELID", partName = "MISSIONLABELID")
        String missionlabelid,
        @WebParam(name = "CONTEXT", partName = "CONTEXT")
        WSOCONTEXT context);

    /**
     * 
     * @param docid
     * @param context
     * @return
     *     returns ru.it.lecm.mobile.services.taskManager.WSOCOLLECTION
     */
    @WebMethod(operationName = "GETMISSIONLABELS", action = "GETMISSIONLABELS")
    @WebResult(name = "GETMISSIONLABELSReturn", partName = "GETMISSIONLABELSReturn")
    public WSOCOLLECTION getmissionlabels(
        @WebParam(name = "DOCID", partName = "DOCID")
        String docid,
        @WebParam(name = "CONTEXT", partName = "CONTEXT")
        WSOCONTEXT context);

    /**
     * 
     * @param includeattachments
     * @param docid
     * @param context
     * @param ismobject
     * @return
     *     returns ru.it.lecm.mobile.services.taskManager.WSOCOLLECTION
     */
    @WebMethod(operationName = "GETRESOLUTIONS", action = "GETRESOLUTIONS")
    @WebResult(name = "GETRESOLUTIONSReturn", partName = "GETRESOLUTIONSReturn")
    public WSOCOLLECTION getresolutions(
        @WebParam(name = "DOCID", partName = "DOCID")
        String docid,
        @WebParam(name = "ISMOBJECT", partName = "ISMOBJECT")
        boolean ismobject,
        @WebParam(name = "INCLUDEATTACHMENTS", partName = "INCLUDEATTACHMENTS")
        boolean includeattachments,
        @WebParam(name = "CONTEXT", partName = "CONTEXT")
        WSOCONTEXT context);

    /**
     * 
     * @param context
     * @param ismobject
     * @return
     *     returns ru.it.lecm.mobile.services.taskManager.WSOCOLLECTION
     */
    @WebMethod(operationName = "GETTASKS", action = "GETTASKS")
    @WebResult(name = "GETTASKSReturn", partName = "GETTASKSReturn")
    public WSOCOLLECTION gettasks(
        @WebParam(name = "ISMOBJECT", partName = "ISMOBJECT")
        boolean ismobject,
        @WebParam(name = "CONTEXT", partName = "CONTEXT")
        WSOCONTEXT context);

    /**
     * 
     * @param context
     * @param doctypename
     * @return
     *     returns ru.it.lecm.mobile.services.taskManager.WSOCOLLECTION
     */
    @WebMethod(operationName = "GETRESTEMPLATES", action = "GETRESTEMPLATES")
    @WebResult(name = "GETRESTEMPLATESReturn", partName = "GETRESTEMPLATESReturn")
    public WSOCOLLECTION getrestemplates(
        @WebParam(name = "DOCTYPENAME", partName = "DOCTYPENAME")
        String doctypename,
        @WebParam(name = "CONTEXT", partName = "CONTEXT")
        WSOCONTEXT context);

    /**
     * 
     * @param context
     * @return
     *     returns ru.it.lecm.mobile.services.taskManager.WSOCOLLECTION
     */
    @WebMethod(operationName = "GETTASKSTEMPLATES", action = "GETTASKSTEMPLATES")
    @WebResult(name = "GETTASKSTEMPLATESReturn", partName = "GETTASKSTEMPLATESReturn")
    public WSOCOLLECTION gettaskstemplates(
        @WebParam(name = "CONTEXT", partName = "CONTEXT")
        WSOCONTEXT context);

    /**
     * 
     * @param context
     * @param inTASK
     * @return
     *     returns ru.it.lecm.mobile.services.taskManager.WSOMTASK
     */
    @WebMethod(operationName = "SETTASK", action = "SETTASK")
    @WebResult(name = "SETTASKReturn", partName = "SETTASKReturn")
    public WSOMTASK settask(
        @WebParam(name = "IN_TASK", partName = "IN_TASK")
        WSOTASK inTASK,
        @WebParam(name = "CONTEXT", partName = "CONTEXT")
        WSOCONTEXT context);

    /**
     * 
     * @param includeattachments
     * @param taskid
     * @param context
     * @param ismobject
     * @return
     *     returns ru.it.lecm.mobile.services.taskManager.WSOCOLLECTION
     */
    @WebMethod(operationName = "GETREPORTS", action = "GETREPORTS")
    @WebResult(name = "GETREPORTSReturn", partName = "GETREPORTSReturn")
    public WSOCOLLECTION getreports(
        @WebParam(name = "TASKID", partName = "TASKID")
        String taskid,
        @WebParam(name = "ISMOBJECT", partName = "ISMOBJECT")
        boolean ismobject,
        @WebParam(name = "INCLUDEATTACHMENTS", partName = "INCLUDEATTACHMENTS")
        boolean includeattachments,
        @WebParam(name = "CONTEXT", partName = "CONTEXT")
        WSOCONTEXT context);

    /**
     * 
     * @param context
     * @param report
     * @return
     *     returns ru.it.lecm.mobile.services.taskManager.WSOMTASKREPORT
     */
    @WebMethod(operationName = "SETREPORT", action = "SETREPORT")
    @WebResult(name = "SETREPORTReturn", partName = "SETREPORTReturn")
    public WSOMTASKREPORT setreport(
        @WebParam(name = "REPORT", partName = "REPORT")
        WSOTASKREPORT report,
        @WebParam(name = "CONTEXT", partName = "CONTEXT")
        WSOCONTEXT context);

    /**
     * 
     * @return
     *     returns ru.it.lecm.mobile.services.taskManager.WSOITEM
     */
    @WebMethod(operationName = "GETITEM", action = "GETITEM")
    @WebResult(name = "GETITEMReturn", partName = "GETITEMReturn")
    public WSOITEM getitem();

}
