
package ru.it.lecm.mobile.services.taskManager;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WS_TaskManagerService",
        targetNamespace = "urn:DefaultNamespace",
        wsdlLocation = "file:WSBR_TaskManager.wsdl")
public class WSTaskManagerService
    extends Service
{

    private final static URL WSTASKMANAGERSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSTASKMANAGERSERVICE_EXCEPTION;
    private final static QName WSTASKMANAGERSERVICE_QNAME = new QName("urn:DefaultNamespace", "WS_TaskManagerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:WSBR_TaskManager.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSTASKMANAGERSERVICE_WSDL_LOCATION = url;
        WSTASKMANAGERSERVICE_EXCEPTION = e;
    }

    public WSTaskManagerService() {
        super(__getWsdlLocation(), WSTASKMANAGERSERVICE_QNAME);
    }

    public WSTaskManagerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSTASKMANAGERSERVICE_QNAME, features);
    }

    public WSTaskManagerService(URL wsdlLocation) {
        super(wsdlLocation, WSTASKMANAGERSERVICE_QNAME);
    }

    public WSTaskManagerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSTASKMANAGERSERVICE_QNAME, features);
    }

    public WSTaskManagerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSTaskManagerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSTaskManager
     */
    @WebEndpoint(name = "Domino")
    public WSTaskManager getDomino() {
        return super.getPort(new QName("urn:DefaultNamespace", "Domino"), WSTaskManager.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSTaskManager
     */
    @WebEndpoint(name = "Domino")
    public WSTaskManager getDomino(WebServiceFeature... features) {
        return super.getPort(new QName("urn:DefaultNamespace", "Domino"), WSTaskManager.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSTASKMANAGERSERVICE_EXCEPTION!= null) {
            throw WSTASKMANAGERSERVICE_EXCEPTION;
        }
        return WSTASKMANAGERSERVICE_WSDL_LOCATION;
    }

}
