
package documentManager;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 */
@WebService(name = "WS_DocumentManager", targetNamespace = "urn:DefaultNamespace")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
        ObjectFactory.class
})
public interface WSDocumentManager {


    /**
     * @param id
     * @param inCONTEXT
     * @return returns ru.it.lecm.wsdl.document.test.WSOMDOCUMENT
     */
    @WebMethod(operationName = "GETDOCUMENT")
    @WebResult(name = "WSO_MDOCUMENT", partName = "WSO_MDOCUMENT")
    public WSOMDOCUMENT getdocument(
            @WebParam(name = "ID", partName = "ID")
            String id,
            @WebParam(name = "IN_CONTEXT", partName = "IN_CONTEXT")
            WSOCONTEXT inCONTEXT);

    /**
     * @param includeattachments
     * @param inCONTEXT
     * @param ismobject
     * @return returns ru.it.lecm.wsdl.document.test.WSOCOLLECTION
     */
    @WebMethod(operationName = "GETDOCUMENTS")
    @WebResult(name = "WSO_COLLECTION", partName = "WSO_COLLECTION")
    public WSOCOLLECTION getdocuments(
            @WebParam(name = "ISMOBJECT", partName = "ISMOBJECT")
            boolean ismobject,
            @WebParam(name = "INCLUDEATTACHMENTS", partName = "INCLUDEATTACHMENTS")
            boolean includeattachments,
            @WebParam(name = "IN_CONTEXT", partName = "IN_CONTEXT")
            WSOCONTEXT inCONTEXT);

    /**
     * @param id
     * @param inCONTEXT
     * @return returns ru.it.lecm.wsdl.document.test.WSOFILE
     */
    @WebMethod(operationName = "GETFILE")
    @WebResult(name = "WSO_FILE", partName = "WSO_FILE")
    public WSOFILE getfile(
            @WebParam(name = "ID", partName = "ID")
            String id,
            @WebParam(name = "IN_CONTEXT", partName = "IN_CONTEXT")
            WSOCONTEXT inCONTEXT);

    @WebMethod
    @WebResult(partName = "return")
    public String ping();

}
