
package ru.it.lecm.integration.referent.services.staffManager;

import ru.it.lecm.integration.referent.objects.*;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WS_StaffManager", targetNamespace = "urn:DefaultNamespace")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSStaffManager {


    /**
     * 
     * @param id
     * @param includeattachments
     * @param context
     * @return
     *     returns ru.it.lecm.integration.referent.objects.WSOGROUP
     */
    @WebMethod
    @WebResult(partName = "return")
    public WSOGROUP getGroup(
        @WebParam(name = "ID", partName = "ID")
        String id,
        @WebParam(name = "INCLUDEATTACHMENTS", partName = "INCLUDEATTACHMENTS")
        boolean includeattachments,
        @WebParam(name = "CONTEXT", partName = "CONTEXT")
        WSOCONTEXT context);

    /**
     * 
     * @param includeattachments
     * @param context
     * @param ismobject
     * @return
     *     returns ru.it.lecm.integration.referent.objects.WSOCOLLECTION
     */
    @WebMethod
    @WebResult(partName = "return")
    public WSOCOLLECTION getOrganizations(
        @WebParam(name = "ISMOBJECT", partName = "ISMOBJECT")
        boolean ismobject,
        @WebParam(name = "INCLUDEATTACHMENTS", partName = "INCLUDEATTACHMENTS")
        boolean includeattachments,
        @WebParam(name = "CONTEXT", partName = "CONTEXT")
        WSOCONTEXT context);

    /**
     * 
     * @param id
     * @param includeattachments
     * @param context
     * @return
     *     returns ru.it.lecm.integration.referent.objects.WSOPERSON
     */
    @WebMethod
    @WebResult(partName = "return")
    public WSOPERSON getPerson(
        @WebParam(name = "ID", partName = "ID")
        String id,
        @WebParam(name = "INCLUDEATTACHMENTS", partName = "INCLUDEATTACHMENTS")
        boolean includeattachments,
        @WebParam(name = "CONTEXT", partName = "CONTEXT")
        WSOCONTEXT context);

    /**
     * 
     * @param personlogin
     * @return
     *     returns ru.it.lecm.integration.referent.objects.WSOBJECT
     */
    @WebMethod
    @WebResult(partName = "return")
    public WSOBJECT getPersonId(
        @WebParam(name = "PERSONLOGIN", partName = "PERSONLOGIN")
        String personlogin);

    /**
     * 
     * @param includeattachments
     * @param context
     * @param groupid
     * @param childslevel
     * @param ismobject
     * @return
     *     returns ru.it.lecm.integration.referent.objects.WSOCOLLECTION
     */
    @WebMethod
    @WebResult(partName = "return")
    public WSOCOLLECTION getPersons(
        @WebParam(name = "GROUPID", partName = "GROUPID")
        String groupid,
        @WebParam(name = "ISMOBJECT", partName = "ISMOBJECT")
        boolean ismobject,
        @WebParam(name = "CHILDSLEVEL", partName = "CHILDSLEVEL")
        int childslevel,
        @WebParam(name = "INCLUDEATTACHMENTS", partName = "INCLUDEATTACHMENTS")
        boolean includeattachments,
        @WebParam(name = "CONTEXT", partName = "CONTEXT")
        WSOCONTEXT context);

    /**
     * 
     * @param includeattachments
     * @param context
     * @param groupid
     * @param childslevel
     * @param ismobject
     * @return
     *     returns ru.it.lecm.integration.referent.objects.WSOGROUP
     */
    @WebMethod
    @WebResult(partName = "return")
    public WSOGROUP getStructure(
        @WebParam(name = "GROUPID", partName = "GROUPID")
        String groupid,
        @WebParam(name = "ISMOBJECT", partName = "ISMOBJECT")
        boolean ismobject,
        @WebParam(name = "CHILDSLEVEL", partName = "CHILDSLEVEL")
        int childslevel,
        @WebParam(name = "INCLUDEATTACHMENTS", partName = "INCLUDEATTACHMENTS")
        boolean includeattachments,
        @WebParam(name = "CONTEXT", partName = "CONTEXT")
        WSOCONTEXT context);
}
