package ru.unicloud.gate;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-04T17:05:22.020+06:00
 * Generated source version: 2.7.5
 * 
 */
@WebServiceClient(name = "GateWcfServiceHttps", 
                  wsdlLocation = "/d:/work/laboratory/GateFlat/GateFlat.wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class GateWcfServiceHttps extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "GateWcfServiceHttps");
    public final static QName WSHttpBindingIGateWcfService = new QName("http://tempuri.org/", "WSHttpBinding_IGateWcfService");
    static {
        URL url = GateWcfServiceHttps.class.getResource("/d:/work/laboratory/GateFlat/GateFlat.wsdl");
        if (url == null) {
            url = GateWcfServiceHttps.class.getClassLoader().getResource("/d:/work/laboratory/GateFlat/GateFlat.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(GateWcfServiceHttps.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "/d:/work/laboratory/GateFlat/GateFlat.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public GateWcfServiceHttps(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GateWcfServiceHttps(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GateWcfServiceHttps() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GateWcfServiceHttps(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GateWcfServiceHttps(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GateWcfServiceHttps(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IGateWcfService
     */
    @WebEndpoint(name = "WSHttpBinding_IGateWcfService")
    public IGateWcfService getWSHttpBindingIGateWcfService() {
        return super.getPort(WSHttpBindingIGateWcfService, IGateWcfService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGateWcfService
     */
    @WebEndpoint(name = "WSHttpBinding_IGateWcfService")
    public IGateWcfService getWSHttpBindingIGateWcfService(WebServiceFeature... features) {
        return super.getPort(WSHttpBindingIGateWcfService, IGateWcfService.class, features);
    }

}
