package ru.unicloud.gate;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.apache.cxf.annotations.DataBinding;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-04T17:05:21.958+06:00
 * Generated source version: 2.7.5
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IGateWcfService")
@DataBinding(org.apache.cxf.xmlbeans.XmlBeansDataBinding.class)
public interface IGateWcfService {

    @Action(input = "http://tempuri.org/IGateWcfService/GenerateTorg12XmlForBuyer", output = "http://tempuri.org/IGateWcfService/GenerateTorg12XmlForBuyerResponse")
    @RequestWrapper(localName = "GenerateTorg12XmlForBuyer", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GenerateTorg12XmlForBuyerDocument")
    @WebMethod(operationName = "GenerateTorg12XmlForBuyer", action = "http://tempuri.org/IGateWcfService/GenerateTorg12XmlForBuyer")
    @ResponseWrapper(localName = "GenerateTorg12XmlForBuyerResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GenerateTorg12XmlForBuyerResponseDocument")
    public void generateTorg12XmlForBuyer(
        @WebParam(name = "vendorId", targetNamespace = "http://tempuri.org/")
        String vendorId,
        @WebParam(name = "buyerId", targetNamespace = "http://tempuri.org/")
        String buyerId,
        @WebParam(name = "opInfo", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas.x2004.x07.uCloudGateProxy.OperatorInfo opInfo,
        @WebParam(name = "date", targetNamespace = "http://tempuri.org/")
        java.util.Calendar date,
        @WebParam(name = "info", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas.x2004.x07.uCloudGateProxyInvoiceClasses.Torg12BuyerTitleInfo info,
        @WebParam(mode = WebParam.Mode.OUT, name = "GenerateTorg12XmlForBuyerResult", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<org.datacontract.schemas.x2004.x07.uCloudGateProxyExceptions.GateResponse> generateTorg12XmlForBuyerResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "generatedDocument", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<org.datacontract.schemas.x2004.x07.uCloudGateProxyGeneratingDocuments.GeneratedDocument1> generatedDocument
    );

    @Action(input = "http://tempuri.org/IGateWcfService/GenerateRegisterRequest", output = "http://tempuri.org/IGateWcfService/GenerateRegisterRequestResponse")
    @RequestWrapper(localName = "GenerateRegisterRequest", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GenerateRegisterRequestDocument")
    @WebMethod(operationName = "GenerateRegisterRequest", action = "http://tempuri.org/IGateWcfService/GenerateRegisterRequest")
    @ResponseWrapper(localName = "GenerateRegisterRequestResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GenerateRegisterRequestResponseDocument")
    public void generateRegisterRequest(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas.x2004.x07.uCloudGateProxyRegistration.RegisterRequestForeignCert request,
        @WebParam(name = "operatorCode", targetNamespace = "http://tempuri.org/")
        String operatorCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "GenerateRegisterRequestResult", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<org.datacontract.schemas.x2004.x07.uCloudGateProxyExceptions.GateResponse> generateRegisterRequestResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "content", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<byte[]> content
    );

    @Action(input = "http://tempuri.org/IGateWcfService/GetDocumentTransportData", output = "http://tempuri.org/IGateWcfService/GetDocumentTransportDataResponse")
    @RequestWrapper(localName = "GetDocumentTransportData", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDocumentTransportDataDocument")
    @WebMethod(operationName = "GetDocumentTransportData", action = "http://tempuri.org/IGateWcfService/GetDocumentTransportData")
    @ResponseWrapper(localName = "GetDocumentTransportDataResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDocumentTransportDataResponseDocument")
    public void getDocumentTransportData(
        @WebParam(name = "sender", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas.x2004.x07.uCloudGateProxy.CompanyInfo sender,
        @WebParam(name = "receiver", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas.x2004.x07.uCloudGateProxy.CompanyInfo receiver,
        @WebParam(name = "prefferableOperatorCode", targetNamespace = "http://tempuri.org/")
        String prefferableOperatorCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetDocumentTransportDataResult", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<org.datacontract.schemas.x2004.x07.uCloudGateProxyExceptions.GateResponse> getDocumentTransportDataResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "transportData", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<org.datacontract.schemas.x2004.x07.uCloudGateProxy.DocumentTransportData> transportData
    );

    @Action(input = "http://tempuri.org/IGateWcfService/AuthenticateByCertificate", output = "http://tempuri.org/IGateWcfService/AuthenticateByCertificateResponse")
    @RequestWrapper(localName = "AuthenticateByCertificate", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AuthenticateByCertificateDocument")
    @WebMethod(operationName = "AuthenticateByCertificate", action = "http://tempuri.org/IGateWcfService/AuthenticateByCertificate")
    @ResponseWrapper(localName = "AuthenticateByCertificateResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AuthenticateByCertificateResponseDocument")
    public void authenticateByCertificate(
        @WebParam(name = "operatorCode", targetNamespace = "http://tempuri.org/")
        String operatorCode,
        @WebParam(name = "signature", targetNamespace = "http://tempuri.org/")
        byte[] signature,
        @WebParam(name = "signedData", targetNamespace = "http://tempuri.org/")
        String signedData,
        @WebParam(mode = WebParam.Mode.OUT, name = "AuthenticateByCertificateResult", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<org.datacontract.schemas.x2004.x07.uCloudGateProxyExceptions.GateResponse> authenticateByCertificateResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "token", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<String> token
    );

    @Action(input = "http://tempuri.org/IGateWcfService/GenerateNotificationXml", output = "http://tempuri.org/IGateWcfService/GenerateNotificationXmlResponse")
    @RequestWrapper(localName = "GenerateNotificationXml", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GenerateNotificationXmlDocument")
    @WebMethod(operationName = "GenerateNotificationXml", action = "http://tempuri.org/IGateWcfService/GenerateNotificationXml")
    @ResponseWrapper(localName = "GenerateNotificationXmlResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GenerateNotificationXmlResponseDocument")
    public void generateNotificationXml(
        @WebParam(name = "signer", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas.x2004.x07.uCloudGateProxyGeneratingDocuments.Signer signer,
        @WebParam(name = "senderCompany", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas.x2004.x07.uCloudGateProxyGeneratingDocumentsCommon.ParticipantBase senderCompany,
        @WebParam(name = "parentDocument", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas.x2004.x07.uCloudGateProxyDocflow.ReceivedDocumentInfo parentDocument,
        @WebParam(name = "generatedDocDate", targetNamespace = "http://tempuri.org/")
        java.util.Calendar generatedDocDate,
        @WebParam(name = "operatorCode", targetNamespace = "http://tempuri.org/")
        String operatorCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "GenerateNotificationXmlResult", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<org.datacontract.schemas.x2004.x07.uCloudGateProxyExceptions.GateResponse> generateNotificationXmlResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "generatedDoc", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<org.datacontract.schemas.x2004.x07.uCloudGateProxyGeneratingDocuments.GeneratedDocument1> generatedDoc
    );

    @WebResult(name = "ClearMailBoxResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IGateWcfService/ClearMailBox", output = "http://tempuri.org/IGateWcfService/ClearMailBoxResponse")
    @RequestWrapper(localName = "ClearMailBox", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ClearMailBoxDocument")
    @WebMethod(operationName = "ClearMailBox", action = "http://tempuri.org/IGateWcfService/ClearMailBox")
    @ResponseWrapper(localName = "ClearMailBoxResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ClearMailBoxResponseDocument")
    public org.datacontract.schemas.x2004.x07.uCloudGateProxyExceptions.GateResponse clearMailBox();

    @Action(input = "http://tempuri.org/IGateWcfService/GetDocflowList", output = "http://tempuri.org/IGateWcfService/GetDocflowListResponse")
    @RequestWrapper(localName = "GetDocflowList", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDocflowListDocument")
    @WebMethod(operationName = "GetDocflowList", action = "http://tempuri.org/IGateWcfService/GetDocflowList")
    @ResponseWrapper(localName = "GetDocflowListResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDocflowListResponseDocument")
    public void getDocflowList(
        @WebParam(name = "filter", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas.x2004.x07.uCloudGateProxy.WorkspaceFilter filter,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetDocflowListResult", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<org.datacontract.schemas.x2004.x07.uCloudGateProxyExceptions.GateResponse> getDocflowListResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "docflows", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<org.datacontract.schemas.x2004.x07.uCloudGateProxy.ArrayOfDocflowInfoBase> docflows
    );

    @Action(input = "http://tempuri.org/IGateWcfService/GetMutualOperators", output = "http://tempuri.org/IGateWcfService/GetMutualOperatorsResponse")
    @RequestWrapper(localName = "GetMutualOperators", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetMutualOperatorsDocument")
    @WebMethod(operationName = "GetMutualOperators", action = "http://tempuri.org/IGateWcfService/GetMutualOperators")
    @ResponseWrapper(localName = "GetMutualOperatorsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetMutualOperatorsResponseDocument")
    public void getMutualOperators(
        @WebParam(name = "sender", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas.x2004.x07.uCloudGateProxy.CompanyInfo sender,
        @WebParam(name = "receiver", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas.x2004.x07.uCloudGateProxy.CompanyInfo receiver,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetMutualOperatorsResult", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<org.datacontract.schemas.x2004.x07.uCloudGateProxyExceptions.GateResponse> getMutualOperatorsResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "operatorCodes", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<com.microsoft.schemas.x2003.x10.serialization.arrays.ArrayOfstring> operatorCodes
    );

    @Action(input = "http://tempuri.org/IGateWcfService/GenerateTorg12XmlForSeller", output = "http://tempuri.org/IGateWcfService/GenerateTorg12XmlForSellerResponse")
    @RequestWrapper(localName = "GenerateTorg12XmlForSeller", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GenerateTorg12XmlForSellerDocument")
    @WebMethod(operationName = "GenerateTorg12XmlForSeller", action = "http://tempuri.org/IGateWcfService/GenerateTorg12XmlForSeller")
    @ResponseWrapper(localName = "GenerateTorg12XmlForSellerResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GenerateTorg12XmlForSellerResponseDocument")
    public void generateTorg12XmlForSeller(
        @WebParam(name = "vendorId", targetNamespace = "http://tempuri.org/")
        String vendorId,
        @WebParam(name = "buyerId", targetNamespace = "http://tempuri.org/")
        String buyerId,
        @WebParam(name = "opInfo", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas.x2004.x07.uCloudGateProxy.OperatorInfo opInfo,
        @WebParam(name = "date", targetNamespace = "http://tempuri.org/")
        java.util.Calendar date,
        @WebParam(name = "info", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas.x2004.x07.uCloudGateProxyInvoiceClasses.Torg12SellerTitleInfo info,
        @WebParam(mode = WebParam.Mode.OUT, name = "GenerateTorg12XmlForSellerResult", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<org.datacontract.schemas.x2004.x07.uCloudGateProxyExceptions.GateResponse> generateTorg12XmlForSellerResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "generatedDoc", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<org.datacontract.schemas.x2004.x07.uCloudGateProxyGeneratingDocuments.GeneratedDocument1> generatedDoc
    );

    @Action(input = "http://tempuri.org/IGateWcfService/RegisterUserByCertificate", output = "http://tempuri.org/IGateWcfService/RegisterUserByCertificateResponse")
    @RequestWrapper(localName = "RegisterUserByCertificate", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RegisterUserByCertificateDocument")
    @WebMethod(operationName = "RegisterUserByCertificate", action = "http://tempuri.org/IGateWcfService/RegisterUserByCertificate")
    @ResponseWrapper(localName = "RegisterUserByCertificateResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RegisterUserByCertificateResponseDocument")
    public void registerUserByCertificate(
        @WebParam(name = "operatorCode", targetNamespace = "http://tempuri.org/")
        String operatorCode,
        @WebParam(name = "partnerKey", targetNamespace = "http://tempuri.org/")
        String partnerKey,
        @WebParam(name = "organizationInn", targetNamespace = "http://tempuri.org/")
        String organizationInn,
        @WebParam(name = "organizationKpp", targetNamespace = "http://tempuri.org/")
        String organizationKpp,
        @WebParam(name = "sign", targetNamespace = "http://tempuri.org/")
        byte[] sign,
        @WebParam(name = "userId", targetNamespace = "http://tempuri.org/")
        String userId,
        @WebParam(mode = WebParam.Mode.OUT, name = "RegisterUserByCertificateResult", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<org.datacontract.schemas.x2004.x07.uCloudGateProxyExceptions.GateResponse> registerUserByCertificateResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "organizationId", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<String> organizationId,
        @WebParam(mode = WebParam.Mode.OUT, name = "organizationEdoId", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<String> organizationEdoId
    );

    @Action(input = "http://tempuri.org/IGateWcfService/GetDocumentContent", output = "http://tempuri.org/IGateWcfService/GetDocumentContentResponse")
    @RequestWrapper(localName = "GetDocumentContent", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDocumentContentDocument")
    @WebMethod(operationName = "GetDocumentContent", action = "http://tempuri.org/IGateWcfService/GetDocumentContent")
    @ResponseWrapper(localName = "GetDocumentContentResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDocumentContentResponseDocument")
    public void getDocumentContent(
        @WebParam(name = "documentId", targetNamespace = "http://tempuri.org/")
        String documentId,
        @WebParam(name = "getSignaturesOnly", targetNamespace = "http://tempuri.org/")
        boolean getSignaturesOnly,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetDocumentContentResult", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<org.datacontract.schemas.x2004.x07.uCloudGateProxyExceptions.GateResponse> getDocumentContentResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "docContent", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<org.datacontract.schemas.x2004.x07.uCloudGateProxy.DocumentContent> docContent
    );

    @Action(input = "http://tempuri.org/IGateWcfService/SendRegisterRequest", output = "http://tempuri.org/IGateWcfService/SendRegisterRequestResponse")
    @RequestWrapper(localName = "SendRegisterRequest", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendRegisterRequestDocument")
    @WebMethod(operationName = "SendRegisterRequest", action = "http://tempuri.org/IGateWcfService/SendRegisterRequest")
    @ResponseWrapper(localName = "SendRegisterRequestResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendRegisterRequestResponseDocument")
    public void sendRegisterRequest(
        @WebParam(name = "requestBinary", targetNamespace = "http://tempuri.org/")
        byte[] requestBinary,
        @WebParam(name = "signature", targetNamespace = "http://tempuri.org/")
        byte[] signature,
        @WebParam(name = "operatorCode", targetNamespace = "http://tempuri.org/")
        String operatorCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "SendRegisterRequestResult", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<org.datacontract.schemas.x2004.x07.uCloudGateProxyExceptions.GateResponse> sendRegisterRequestResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "requestId", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<String> requestId
    );

    @Action(input = "http://tempuri.org/IGateWcfService/GetServiceVersion", output = "http://tempuri.org/IGateWcfService/GetServiceVersionResponse")
    @RequestWrapper(localName = "GetServiceVersion", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetServiceVersionDocument")
    @WebMethod(operationName = "GetServiceVersion", action = "http://tempuri.org/IGateWcfService/GetServiceVersion")
    @ResponseWrapper(localName = "GetServiceVersionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetServiceVersionResponseDocument")
    public void getServiceVersion(
        @WebParam(mode = WebParam.Mode.OUT, name = "GetServiceVersionResult", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<org.datacontract.schemas.x2004.x07.uCloudGateProxyExceptions.GateResponse> getServiceVersionResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "version", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<String> version
    );

    @Action(input = "http://tempuri.org/IGateWcfService/GetDocumentList", output = "http://tempuri.org/IGateWcfService/GetDocumentListResponse")
    @RequestWrapper(localName = "GetDocumentList", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDocumentListDocument")
    @WebMethod(operationName = "GetDocumentList", action = "http://tempuri.org/IGateWcfService/GetDocumentList")
    @ResponseWrapper(localName = "GetDocumentListResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDocumentListResponseDocument")
    public void getDocumentList(
        @WebParam(name = "docflowId", targetNamespace = "http://tempuri.org/")
        String docflowId,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetDocumentListResult", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<org.datacontract.schemas.x2004.x07.uCloudGateProxyExceptions.GateResponse> getDocumentListResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "documentInfos", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<org.datacontract.schemas.x2004.x07.uCloudGateProxy.ArrayOfDocumentInfo> documentInfos
    );

    @Action(input = "http://tempuri.org/IGateWcfService/GetOperators", output = "http://tempuri.org/IGateWcfService/GetOperatorsResponse")
    @RequestWrapper(localName = "GetOperators", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOperatorsDocument")
    @WebMethod(operationName = "GetOperators", action = "http://tempuri.org/IGateWcfService/GetOperators")
    @ResponseWrapper(localName = "GetOperatorsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOperatorsResponseDocument")
    public void getOperators(
        @WebParam(mode = WebParam.Mode.OUT, name = "GetOperatorsResult", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<org.datacontract.schemas.x2004.x07.uCloudGateProxyExceptions.GateResponse> getOperatorsResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "operatorInfos", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<org.datacontract.schemas.x2004.x07.uCloudGateProxy.ArrayOfOperatorInfo> operatorInfos
    );

    @WebResult(name = "StartSmsAuthenticationResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IGateWcfService/StartSmsAuthentication", output = "http://tempuri.org/IGateWcfService/StartSmsAuthenticationResponse")
    @RequestWrapper(localName = "StartSmsAuthentication", targetNamespace = "http://tempuri.org/", className = "org.tempuri.StartSmsAuthenticationDocument")
    @WebMethod(operationName = "StartSmsAuthentication", action = "http://tempuri.org/IGateWcfService/StartSmsAuthentication")
    @ResponseWrapper(localName = "StartSmsAuthenticationResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.StartSmsAuthenticationResponseDocument")
    public org.datacontract.schemas.x2004.x07.uCloudGateProxyExceptions.GateResponse startSmsAuthentication(
        @WebParam(name = "operatorCode", targetNamespace = "http://tempuri.org/")
        String operatorCode
    );

    @Action(input = "http://tempuri.org/IGateWcfService/GenerateInvoiceXml", output = "http://tempuri.org/IGateWcfService/GenerateInvoiceXmlResponse")
    @RequestWrapper(localName = "GenerateInvoiceXml", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GenerateInvoiceXmlDocument")
    @WebMethod(operationName = "GenerateInvoiceXml", action = "http://tempuri.org/IGateWcfService/GenerateInvoiceXml")
    @ResponseWrapper(localName = "GenerateInvoiceXmlResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GenerateInvoiceXmlResponseDocument")
    public void generateInvoiceXml(
        @WebParam(name = "invoice", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas.x2004.x07.uCloudGateProxyGeneratingDocumentsInvoice.InvoiceGen invoice,
        @WebParam(name = "operatorCode", targetNamespace = "http://tempuri.org/")
        String operatorCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "GenerateInvoiceXmlResult", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<org.datacontract.schemas.x2004.x07.uCloudGateProxyExceptions.GateResponse> generateInvoiceXmlResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "generatedDoc", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<org.datacontract.schemas.x2004.x07.uCloudGateProxy.DocumentToSend> generatedDoc
    );

    @Action(input = "http://tempuri.org/IGateWcfService/CheckIfPersonIsEmployeeByCertificate", output = "http://tempuri.org/IGateWcfService/CheckIfPersonIsEmployeeByCertificateResponse")
    @RequestWrapper(localName = "CheckIfPersonIsEmployeeByCertificate", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CheckIfPersonIsEmployeeByCertificateDocument")
    @WebMethod(operationName = "CheckIfPersonIsEmployeeByCertificate", action = "http://tempuri.org/IGateWcfService/CheckIfPersonIsEmployeeByCertificate")
    @ResponseWrapper(localName = "CheckIfPersonIsEmployeeByCertificateResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CheckIfPersonIsEmployeeByCertificateResponseDocument")
    public void checkIfPersonIsEmployeeByCertificate(
        @WebParam(name = "certificate", targetNamespace = "http://tempuri.org/")
        byte[] certificate,
        @WebParam(name = "operatorCode", targetNamespace = "http://tempuri.org/")
        String operatorCode,
        @WebParam(name = "organizationInn", targetNamespace = "http://tempuri.org/")
        String organizationInn,
        @WebParam(name = "organizationKpp", targetNamespace = "http://tempuri.org/")
        String organizationKpp,
        @WebParam(mode = WebParam.Mode.OUT, name = "CheckIfPersonIsEmployeeByCertificateResult", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<org.datacontract.schemas.x2004.x07.uCloudGateProxyExceptions.GateResponse> checkIfPersonIsEmployeeByCertificateResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "isEmployee", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.Boolean> isEmployee
    );

    @Action(input = "http://tempuri.org/IGateWcfService/FinishSmsAuthentication", output = "http://tempuri.org/IGateWcfService/FinishSmsAuthenticationResponse")
    @RequestWrapper(localName = "FinishSmsAuthentication", targetNamespace = "http://tempuri.org/", className = "org.tempuri.FinishSmsAuthenticationDocument")
    @WebMethod(operationName = "FinishSmsAuthentication", action = "http://tempuri.org/IGateWcfService/FinishSmsAuthentication")
    @ResponseWrapper(localName = "FinishSmsAuthenticationResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.FinishSmsAuthenticationResponseDocument")
    public void finishSmsAuthentication(
        @WebParam(name = "operatorCode", targetNamespace = "http://tempuri.org/")
        String operatorCode,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(mode = WebParam.Mode.OUT, name = "FinishSmsAuthenticationResult", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<org.datacontract.schemas.x2004.x07.uCloudGateProxyExceptions.GateResponse> finishSmsAuthenticationResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "token", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<String> token
    );

    @Action(input = "http://tempuri.org/IGateWcfService/SendDocument", output = "http://tempuri.org/IGateWcfService/SendDocumentResponse")
    @RequestWrapper(localName = "SendDocument", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendDocumentDocument1")
    @WebMethod(operationName = "SendDocument", action = "http://tempuri.org/IGateWcfService/SendDocument")
    @ResponseWrapper(localName = "SendDocumentResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendDocumentResponseDocument")
    public void sendDocument(
        @WebParam(name = "doc", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas.x2004.x07.uCloudGateProxy.DocumentToSend doc,
        @WebParam(name = "operatorCode", targetNamespace = "http://tempuri.org/")
        String operatorCode,
        @WebParam(name = "billingTicket", targetNamespace = "http://tempuri.org/")
        String billingTicket,
        @WebParam(mode = WebParam.Mode.OUT, name = "SendDocumentResult", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<org.datacontract.schemas.x2004.x07.uCloudGateProxyExceptions.GateResponse> sendDocumentResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "documentId", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<String> documentId
    );

    @Action(input = "http://tempuri.org/IGateWcfService/GetRegistrationInfo", output = "http://tempuri.org/IGateWcfService/GetRegistrationInfoResponse")
    @RequestWrapper(localName = "GetRegistrationInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRegistrationInfoDocument")
    @WebMethod(operationName = "GetRegistrationInfo", action = "http://tempuri.org/IGateWcfService/GetRegistrationInfo")
    @ResponseWrapper(localName = "GetRegistrationInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRegistrationInfoResponseDocument")
    public void getRegistrationInfo(
        @WebParam(mode = WebParam.Mode.OUT, name = "GetRegistrationInfoResult", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<org.datacontract.schemas.x2004.x07.uCloudGateProxyExceptions.GateResponse> getRegistrationInfoResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "registrationInfos", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<org.datacontract.schemas.x2004.x07.uCloudGateProxy.ArrayOfRegistrationInfo> registrationInfos
    );

    @WebResult(name = "StartRegisterUserBySmsResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IGateWcfService/StartRegisterUserBySms", output = "http://tempuri.org/IGateWcfService/StartRegisterUserBySmsResponse")
    @RequestWrapper(localName = "StartRegisterUserBySms", targetNamespace = "http://tempuri.org/", className = "org.tempuri.StartRegisterUserBySmsDocument")
    @WebMethod(operationName = "StartRegisterUserBySms", action = "http://tempuri.org/IGateWcfService/StartRegisterUserBySms")
    @ResponseWrapper(localName = "StartRegisterUserBySmsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.StartRegisterUserBySmsResponseDocument")
    public org.datacontract.schemas.x2004.x07.uCloudGateProxyExceptions.GateResponse startRegisterUserBySms(
        @WebParam(name = "operatorCode", targetNamespace = "http://tempuri.org/")
        String operatorCode,
        @WebParam(name = "mobileNumber", targetNamespace = "http://tempuri.org/")
        String mobileNumber,
        @WebParam(name = "inn", targetNamespace = "http://tempuri.org/")
        String inn,
        @WebParam(name = "kpp", targetNamespace = "http://tempuri.org/")
        String kpp
    );

    @Action(input = "http://tempuri.org/IGateWcfService/VerifySignature", output = "http://tempuri.org/IGateWcfService/VerifySignatureResponse")
    @RequestWrapper(localName = "VerifySignature", targetNamespace = "http://tempuri.org/", className = "org.tempuri.VerifySignatureDocument")
    @WebMethod(operationName = "VerifySignature", action = "http://tempuri.org/IGateWcfService/VerifySignature")
    @ResponseWrapper(localName = "VerifySignatureResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.VerifySignatureResponseDocument")
    public void verifySignature(
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        byte[] content,
        @WebParam(name = "signature", targetNamespace = "http://tempuri.org/")
        byte[] signature,
        @WebParam(name = "operatorCode", targetNamespace = "http://tempuri.org/")
        String operatorCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "VerifySignatureResult", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<org.datacontract.schemas.x2004.x07.uCloudGateProxyExceptions.GateResponse> verifySignatureResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "signerInfo", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<String> signerInfo,
        @WebParam(mode = WebParam.Mode.OUT, name = "isSignatureValid", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.Boolean> isSignatureValid
    );

    @WebResult(name = "SetBillingAccountToOrganizationResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IGateWcfService/SetBillingAccountToOrganization", output = "http://tempuri.org/IGateWcfService/SetBillingAccountToOrganizationResponse")
    @RequestWrapper(localName = "SetBillingAccountToOrganization", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SetBillingAccountToOrganizationDocument")
    @WebMethod(operationName = "SetBillingAccountToOrganization", action = "http://tempuri.org/IGateWcfService/SetBillingAccountToOrganization")
    @ResponseWrapper(localName = "SetBillingAccountToOrganizationResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SetBillingAccountToOrganizationResponseDocument")
    public org.datacontract.schemas.x2004.x07.uCloudGateProxyExceptions.GateResponse setBillingAccountToOrganization(
        @WebParam(name = "operatorCode", targetNamespace = "http://tempuri.org/")
        String operatorCode,
        @WebParam(name = "signature", targetNamespace = "http://tempuri.org/")
        byte[] signature,
        @WebParam(name = "billingLogin", targetNamespace = "http://tempuri.org/")
        String billingLogin,
        @WebParam(name = "billingPassword", targetNamespace = "http://tempuri.org/")
        String billingPassword,
        @WebParam(name = "existedAccount", targetNamespace = "http://tempuri.org/")
        boolean existedAccount
    );

    @Action(input = "http://tempuri.org/IGateWcfService/SignDocument", output = "http://tempuri.org/IGateWcfService/SignDocumentResponse")
    @RequestWrapper(localName = "SignDocument", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SignDocumentDocument1")
    @WebMethod(operationName = "SignDocument", action = "http://tempuri.org/IGateWcfService/SignDocument")
    @ResponseWrapper(localName = "SignDocumentResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SignDocumentResponseDocument")
    public void signDocument(
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        byte[] content,
        @WebParam(name = "operatorCode", targetNamespace = "http://tempuri.org/")
        String operatorCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "SignDocumentResult", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<org.datacontract.schemas.x2004.x07.uCloudGateProxyExceptions.GateResponse> signDocumentResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "signature", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<byte[]> signature
    );

    @Action(input = "http://tempuri.org/IGateWcfService/GetRegisterResponse", output = "http://tempuri.org/IGateWcfService/GetRegisterResponseResponse")
    @RequestWrapper(localName = "GetRegisterResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRegisterResponseDocument")
    @WebMethod(operationName = "GetRegisterResponse", action = "http://tempuri.org/IGateWcfService/GetRegisterResponse")
    @ResponseWrapper(localName = "GetRegisterResponseResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRegisterResponseResponseDocument")
    public void getRegisterResponse(
        @WebParam(name = "packetId", targetNamespace = "http://tempuri.org/")
        String packetId,
        @WebParam(name = "operatorCode", targetNamespace = "http://tempuri.org/")
        String operatorCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetRegisterResponseResult", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<org.datacontract.schemas.x2004.x07.uCloudGateProxyExceptions.GateResponse> getRegisterResponseResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "operatorResponse", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<org.datacontract.schemas.x2004.x07.uCloudGateProxyRegistration.RegisterResponse> operatorResponse
    );

    @Action(input = "http://tempuri.org/IGateWcfService/FinishRegisterUserBySms", output = "http://tempuri.org/IGateWcfService/FinishRegisterUserBySmsResponse")
    @RequestWrapper(localName = "FinishRegisterUserBySms", targetNamespace = "http://tempuri.org/", className = "org.tempuri.FinishRegisterUserBySmsDocument")
    @WebMethod(operationName = "FinishRegisterUserBySms", action = "http://tempuri.org/IGateWcfService/FinishRegisterUserBySms")
    @ResponseWrapper(localName = "FinishRegisterUserBySmsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.FinishRegisterUserBySmsResponseDocument")
    public void finishRegisterUserBySms(
        @WebParam(name = "operatorCode", targetNamespace = "http://tempuri.org/")
        String operatorCode,
        @WebParam(name = "mobileNumber", targetNamespace = "http://tempuri.org/")
        String mobileNumber,
        @WebParam(name = "partnerKey", targetNamespace = "http://tempuri.org/")
        String partnerKey,
        @WebParam(name = "inn", targetNamespace = "http://tempuri.org/")
        String inn,
        @WebParam(name = "kpp", targetNamespace = "http://tempuri.org/")
        String kpp,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "userIdByPartnerSystem", targetNamespace = "http://tempuri.org/")
        String userIdByPartnerSystem,
        @WebParam(mode = WebParam.Mode.OUT, name = "FinishRegisterUserBySmsResult", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<org.datacontract.schemas.x2004.x07.uCloudGateProxyExceptions.GateResponse> finishRegisterUserBySmsResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "organizationId", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<String> organizationId,
        @WebParam(mode = WebParam.Mode.OUT, name = "organizationEdoId", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<String> organizationEdoId
    );

    @Action(input = "http://tempuri.org/IGateWcfService/ParseInvoiceCorrectionRequestXml", output = "http://tempuri.org/IGateWcfService/ParseInvoiceCorrectionRequestXmlResponse")
    @RequestWrapper(localName = "ParseInvoiceCorrectionRequestXml", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ParseInvoiceCorrectionRequestXmlDocument")
    @WebMethod(operationName = "ParseInvoiceCorrectionRequestXml", action = "http://tempuri.org/IGateWcfService/ParseInvoiceCorrectionRequestXml")
    @ResponseWrapper(localName = "ParseInvoiceCorrectionRequestXmlResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ParseInvoiceCorrectionRequestXmlResponseDocument")
    public void parseInvoiceCorrectionRequestXml(
        @WebParam(name = "xml", targetNamespace = "http://tempuri.org/")
        byte[] xml,
        @WebParam(mode = WebParam.Mode.OUT, name = "ParseInvoiceCorrectionRequestXmlResult", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<org.datacontract.schemas.x2004.x07.uCloudGateProxyExceptions.GateResponse> parseInvoiceCorrectionRequestXmlResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "requestText", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<String> requestText
    );

    @WebResult(name = "MarkDocflowsAsReadResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IGateWcfService/MarkDocflowsAsRead", output = "http://tempuri.org/IGateWcfService/MarkDocflowsAsReadResponse")
    @RequestWrapper(localName = "MarkDocflowsAsRead", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MarkDocflowsAsReadDocument")
    @WebMethod(operationName = "MarkDocflowsAsRead", action = "http://tempuri.org/IGateWcfService/MarkDocflowsAsRead")
    @ResponseWrapper(localName = "MarkDocflowsAsReadResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MarkDocflowsAsReadResponseDocument")
    public org.datacontract.schemas.x2004.x07.uCloudGateProxyExceptions.GateResponse markDocflowsAsRead(
        @WebParam(name = "docflowIdArray", targetNamespace = "http://tempuri.org/")
        com.microsoft.schemas.x2003.x10.serialization.arrays.ArrayOfguid docflowIdArray
    );

    @Action(input = "http://tempuri.org/IGateWcfService/GenerateInvoiceCorrectionRequestXml", output = "http://tempuri.org/IGateWcfService/GenerateInvoiceCorrectionRequestXmlResponse")
    @RequestWrapper(localName = "GenerateInvoiceCorrectionRequestXml", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GenerateInvoiceCorrectionRequestXmlDocument")
    @WebMethod(operationName = "GenerateInvoiceCorrectionRequestXml", action = "http://tempuri.org/IGateWcfService/GenerateInvoiceCorrectionRequestXml")
    @ResponseWrapper(localName = "GenerateInvoiceCorrectionRequestXmlResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GenerateInvoiceCorrectionRequestXmlResponseDocument")
    public void generateInvoiceCorrectionRequestXml(
        @WebParam(name = "correctionRequest", targetNamespace = "http://tempuri.org/")
        org.datacontract.schemas.x2004.x07.uCloudGateProxyGeneratingDocumentsInvoice.CorrectionRequest correctionRequest,
        @WebParam(mode = WebParam.Mode.OUT, name = "GenerateInvoiceCorrectionRequestXmlResult", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<org.datacontract.schemas.x2004.x07.uCloudGateProxyExceptions.GateResponse> generateInvoiceCorrectionRequestXmlResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "generatedDocument", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<org.datacontract.schemas.x2004.x07.uCloudGateProxyGeneratingDocuments.GeneratedDocument1> generatedDocument
    );
}
